version: 2
linters:
  enable:
    - bodyclose
    - gocognit
    - gocritic
    - gocyclo
    - gosec
    - prealloc
    - unconvert
  exclusions:
    rules:
      - path: '(.+)_test\.go'
        linters:
          - gosec
      - path: 'pkg/problems/many/wfg/'
        linters:
          - gocritic
          - prealloc
      - path: 'cmd/decli/internal/commands/root\.go'
        linters:
          - gosec
      - path: 'internal/server/server\.go'
        linters:
          - gosec
      - path: 'internal/server/handlers/differential_evolution\.go'
        linters:
          - gosec
      - path: 'pkg/de/gde3/gde3\.go'
        linters:
          - gosec
      - path: 'pkg/variants/pbest/pbest\.go'
        linters:
          - gosec
      - path: 'pkg/problems/multi/'
        linters:
          - gocritic

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true
    exclude-functions:
      - (io.Closer).Close
  gocognit:
    min-complexity: 20
  gocyclo:
    min-complexity: 15
  govet:
    disable:
      - shadow
    enable-all: true

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  exclude-dirs:
    - third_party
    - builtin
    - examples
