version: 2
linters:
  enable:
    - bodyclose
    - gocognit
    - gocritic
    - gocyclo
    - gosec
    - prealloc
    - revive
    - unconvert
  exclusions:
    rules:
      - path: '(.+)_test\.go'
        linters:
          - gosec
      - path: 'pkg/problems/many/wfg/'
        linters:
          - gocritic
          - prealloc
      - path: 'cmd/decli/internal/commands/root\.go'
        linters:
          - gosec
      - path: 'internal/server/server\.go'
        linters:
          - gosec
      - path: 'internal/server/handlers/differential_evolution\.go'
        linters:
          - gosec
      - path: 'pkg/de/gde3/gde3\.go'
        linters:
          - gosec
      - path: 'pkg/variants/pbest/pbest\.go'
        linters:
          - gosec
      - path: 'cmd/decli/internal/commands/'
        linters:
          - revive
      - path: 'cmd/deserver/internal/commands/'
        linters:
          - revive
      - path: 'internal/server/handlers/'
        linters:
          - revive
      - path: 'internal/log/log\.go'
        linters:
          - revive
      - path: 'cmd/decli/internal/state/sqlite/sqlite\.go'
        linters:
          - revive
      - path: 'cmd/decli/internal/utils/'
        linters:
          - revive
      - path: 'internal/server/lifecycle\.go'
        linters:
          - revive
      - path: 'internal/server/middleware/'
        linters:
          - revive
      - path: 'internal/store/'
        linters:
          - revive
      - path: 'pkg/validation/'
        linters:
          - revive
      - path: 'internal/server/options\.go'
        linters:
          - revive
      - path: 'internal/telemetry/'
        linters:
          - revive
      - path: 'pkg/de/'
        linters:
          - revive
      - path: 'pkg/problems/'
        linters:
          - revive
          - gocritic
      - path: 'internal/server/server\.go'
        linters:
          - revive

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true
    exclude-functions:
      - (io.Closer).Close
  gocognit:
    min-complexity: 20
  gocyclo:
    min-complexity: 15
  govet:
    disable:
      - shadow
    enable-all: true
  revive:
    rules:
      - name: exported
        disabled: true
      - name: package-comments
        disabled: false
      - name: unused-parameter
        disabled: true

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  exclude-dirs:
    - third_party
    - builtin
    - examples
