version: 2
linters:
  enable:
    - bodyclose
    - gocognit
    - gocritic
    - gocyclo
    - gosec
    - prealloc
    - revive
    - unconvert

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true
    exclude-functions:
      - (io.Closer).Close
  gocognit:
    min-complexity: 20
  gocyclo:
    min-complexity: 15
  gosec:
    excludes:
      - G104  # Unchecked errors (handled by errcheck linter)
      - G108  # Profiling endpoint (pprof) - acceptable for development/debugging
      - G404  # Weak random generator - math/rand is acceptable for DE algorithms and tests
  govet:
    disable:
      - shadow
    enable-all: true
  revive:
    rules:
      - name: exported
        disabled: true
      - name: package-comments
        disabled: false

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  exclude-rules:
    - linters:
        - errcheck
        - gocyclo
        - gosec
        - unused
      path: _test\.go
    - linters:
        - all
      path: .*\.pb\.go$
    - linters:
        - all
      path: .*\.pb\.gw\.go$
  exclude-dirs:
    - third_party
    - builtin
    - examples
