// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: api/v1/auth.proto

package api

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AuthServiceRegisterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *User                  `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthServiceRegisterRequest) Reset() {
	*x = AuthServiceRegisterRequest{}
	mi := &file_api_v1_auth_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthServiceRegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthServiceRegisterRequest) ProtoMessage() {}

func (x *AuthServiceRegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_auth_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthServiceRegisterRequest.ProtoReflect.Descriptor instead.
func (*AuthServiceRegisterRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_auth_proto_rawDescGZIP(), []int{0}
}

func (x *AuthServiceRegisterRequest) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

type AuthServiceLoginRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthServiceLoginRequest) Reset() {
	*x = AuthServiceLoginRequest{}
	mi := &file_api_v1_auth_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthServiceLoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthServiceLoginRequest) ProtoMessage() {}

func (x *AuthServiceLoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_auth_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthServiceLoginRequest.ProtoReflect.Descriptor instead.
func (*AuthServiceLoginRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_auth_proto_rawDescGZIP(), []int{1}
}

func (x *AuthServiceLoginRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *AuthServiceLoginRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type AuthServiceLoginResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthServiceLoginResponse) Reset() {
	*x = AuthServiceLoginResponse{}
	mi := &file_api_v1_auth_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthServiceLoginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthServiceLoginResponse) ProtoMessage() {}

func (x *AuthServiceLoginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_auth_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthServiceLoginResponse.ProtoReflect.Descriptor instead.
func (*AuthServiceLoginResponse) Descriptor() ([]byte, []int) {
	return file_api_v1_auth_proto_rawDescGZIP(), []int{2}
}

func (x *AuthServiceLoginResponse) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type AuthServiceLogoutRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthServiceLogoutRequest) Reset() {
	*x = AuthServiceLogoutRequest{}
	mi := &file_api_v1_auth_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthServiceLogoutRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthServiceLogoutRequest) ProtoMessage() {}

func (x *AuthServiceLogoutRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_auth_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthServiceLogoutRequest.ProtoReflect.Descriptor instead.
func (*AuthServiceLogoutRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_auth_proto_rawDescGZIP(), []int{3}
}

func (x *AuthServiceLogoutRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

var File_api_v1_auth_proto protoreflect.FileDescriptor

const file_api_v1_auth_proto_rawDesc = "" +
	"\n" +
	"\x11api/v1/auth.proto\x12\x06api.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a\x11api/v1/user.proto\">\n" +
	"\x1aAuthServiceRegisterRequest\x12 \n" +
	"\x04user\x18\x01 \x01(\v2\f.api.v1.UserR\x04user\"Q\n" +
	"\x17AuthServiceLoginRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"0\n" +
	"\x18AuthServiceLoginResponse\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\"6\n" +
	"\x18AuthServiceLogoutRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername2\xba\x02\n" +
	"\vAuthService\x12d\n" +
	"\bRegister\x12\".api.v1.AuthServiceRegisterRequest\x1a\x16.google.protobuf.Empty\"\x1c\x82\xd3\xe4\x93\x02\x16:\x01*\"\x11/v1/auth/register\x12e\n" +
	"\x05Login\x12\x1f.api.v1.AuthServiceLoginRequest\x1a .api.v1.AuthServiceLoginResponse\"\x19\x82\xd3\xe4\x93\x02\x13:\x01*\"\x0e/v1/auth/login\x12^\n" +
	"\x06Logout\x12 .api.v1.AuthServiceLogoutRequest\x1a\x16.google.protobuf.Empty\"\x1a\x82\xd3\xe4\x93\x02\x14:\x01*\"\x0f/v1/auth/logoutB\tZ\apkg/apib\x06proto3"

var (
	file_api_v1_auth_proto_rawDescOnce sync.Once
	file_api_v1_auth_proto_rawDescData []byte
)

func file_api_v1_auth_proto_rawDescGZIP() []byte {
	file_api_v1_auth_proto_rawDescOnce.Do(func() {
		file_api_v1_auth_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_v1_auth_proto_rawDesc), len(file_api_v1_auth_proto_rawDesc)))
	})
	return file_api_v1_auth_proto_rawDescData
}

var file_api_v1_auth_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_api_v1_auth_proto_goTypes = []any{
	(*AuthServiceRegisterRequest)(nil), // 0: api.v1.AuthServiceRegisterRequest
	(*AuthServiceLoginRequest)(nil),    // 1: api.v1.AuthServiceLoginRequest
	(*AuthServiceLoginResponse)(nil),   // 2: api.v1.AuthServiceLoginResponse
	(*AuthServiceLogoutRequest)(nil),   // 3: api.v1.AuthServiceLogoutRequest
	(*User)(nil),                       // 4: api.v1.User
	(*emptypb.Empty)(nil),              // 5: google.protobuf.Empty
}
var file_api_v1_auth_proto_depIdxs = []int32{
	4, // 0: api.v1.AuthServiceRegisterRequest.user:type_name -> api.v1.User
	0, // 1: api.v1.AuthService.Register:input_type -> api.v1.AuthServiceRegisterRequest
	1, // 2: api.v1.AuthService.Login:input_type -> api.v1.AuthServiceLoginRequest
	3, // 3: api.v1.AuthService.Logout:input_type -> api.v1.AuthServiceLogoutRequest
	5, // 4: api.v1.AuthService.Register:output_type -> google.protobuf.Empty
	2, // 5: api.v1.AuthService.Login:output_type -> api.v1.AuthServiceLoginResponse
	5, // 6: api.v1.AuthService.Logout:output_type -> google.protobuf.Empty
	4, // [4:7] is the sub-list for method output_type
	1, // [1:4] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_api_v1_auth_proto_init() }
func file_api_v1_auth_proto_init() {
	if File_api_v1_auth_proto != nil {
		return
	}
	file_api_v1_user_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_v1_auth_proto_rawDesc), len(file_api_v1_auth_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_v1_auth_proto_goTypes,
		DependencyIndexes: file_api_v1_auth_proto_depIdxs,
		MessageInfos:      file_api_v1_auth_proto_msgTypes,
	}.Build()
	File_api_v1_auth_proto = out.File
	file_api_v1_auth_proto_goTypes = nil
	file_api_v1_auth_proto_depIdxs = nil
}
