// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.1
// 	protoc        (unknown)
// source: api/v1/definitions.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// VectorIDs contain identifiers for a population.
type VectorIDs struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VectorIDs) Reset() {
	*x = VectorIDs{}
	mi := &file_api_v1_definitions_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VectorIDs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VectorIDs) ProtoMessage() {}

func (x *VectorIDs) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_definitions_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VectorIDs.ProtoReflect.Descriptor instead.
func (*VectorIDs) Descriptor() ([]byte, []int) {
	return file_api_v1_definitions_proto_rawDescGZIP(), []int{0}
}

func (x *VectorIDs) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

// Vector is an element used in the Differential Evoluition algorithm.
type Vector struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Ids              *VectorIDs             `protobuf:"bytes,1,opt,name=ids,proto3" json:"ids,omitempty"`
	Elements         []float64              `protobuf:"fixed64,2,rep,packed,name=elements,proto3" json:"elements,omitempty"`
	Objectives       []float64              `protobuf:"fixed64,3,rep,packed,name=objectives,proto3" json:"objectives,omitempty"`
	CrowdingDistance float64                `protobuf:"fixed64,4,opt,name=crowding_distance,json=crowdingDistance,proto3" json:"crowding_distance,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Vector) Reset() {
	*x = Vector{}
	mi := &file_api_v1_definitions_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Vector) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Vector) ProtoMessage() {}

func (x *Vector) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_definitions_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Vector.ProtoReflect.Descriptor instead.
func (*Vector) Descriptor() ([]byte, []int) {
	return file_api_v1_definitions_proto_rawDescGZIP(), []int{1}
}

func (x *Vector) GetIds() *VectorIDs {
	if x != nil {
		return x.Ids
	}
	return nil
}

func (x *Vector) GetElements() []float64 {
	if x != nil {
		return x.Elements
	}
	return nil
}

func (x *Vector) GetObjectives() []float64 {
	if x != nil {
		return x.Objectives
	}
	return nil
}

func (x *Vector) GetCrowdingDistance() float64 {
	if x != nil {
		return x.CrowdingDistance
	}
	return 0
}

// PopulationParameters are the values used by a Population in a generation.
type PopulationParameters struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	PopulationSize int64                  `protobuf:"varint,1,opt,name=population_size,json=populationSize,proto3" json:"population_size,omitempty"`
	DimensionsSize int64                  `protobuf:"varint,2,opt,name=dimensions_size,json=dimensionsSize,proto3" json:"dimensions_size,omitempty"`
	ObjetivesSize  int64                  `protobuf:"varint,3,opt,name=objetives_size,json=objetivesSize,proto3" json:"objetives_size,omitempty"`
	Floors         []float64              `protobuf:"fixed64,4,rep,packed,name=floors,proto3" json:"floors,omitempty"`
	Ceils          []float64              `protobuf:"fixed64,5,rep,packed,name=ceils,proto3" json:"ceils,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *PopulationParameters) Reset() {
	*x = PopulationParameters{}
	mi := &file_api_v1_definitions_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PopulationParameters) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PopulationParameters) ProtoMessage() {}

func (x *PopulationParameters) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_definitions_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PopulationParameters.ProtoReflect.Descriptor instead.
func (*PopulationParameters) Descriptor() ([]byte, []int) {
	return file_api_v1_definitions_proto_rawDescGZIP(), []int{2}
}

func (x *PopulationParameters) GetPopulationSize() int64 {
	if x != nil {
		return x.PopulationSize
	}
	return 0
}

func (x *PopulationParameters) GetDimensionsSize() int64 {
	if x != nil {
		return x.DimensionsSize
	}
	return 0
}

func (x *PopulationParameters) GetObjetivesSize() int64 {
	if x != nil {
		return x.ObjetivesSize
	}
	return 0
}

func (x *PopulationParameters) GetFloors() []float64 {
	if x != nil {
		return x.Floors
	}
	return nil
}

func (x *PopulationParameters) GetCeils() []float64 {
	if x != nil {
		return x.Ceils
	}
	return nil
}

type ParetoIDs struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ParetoIDs) Reset() {
	*x = ParetoIDs{}
	mi := &file_api_v1_definitions_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ParetoIDs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ParetoIDs) ProtoMessage() {}

func (x *ParetoIDs) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_definitions_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ParetoIDs.ProtoReflect.Descriptor instead.
func (*ParetoIDs) Descriptor() ([]byte, []int) {
	return file_api_v1_definitions_proto_rawDescGZIP(), []int{3}
}

func (x *ParetoIDs) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ParetoIDs) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type Pareto struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ids           *ParetoIDs             `protobuf:"bytes,1,opt,name=ids,proto3" json:"ids,omitempty"`
	Vectors       []*Vector              `protobuf:"bytes,2,rep,name=vectors,proto3" json:"vectors,omitempty"`
	MaxObjs       []float64              `protobuf:"fixed64,3,rep,packed,name=max_objs,json=maxObjs,proto3" json:"max_objs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Pareto) Reset() {
	*x = Pareto{}
	mi := &file_api_v1_definitions_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Pareto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Pareto) ProtoMessage() {}

func (x *Pareto) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_definitions_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Pareto.ProtoReflect.Descriptor instead.
func (*Pareto) Descriptor() ([]byte, []int) {
	return file_api_v1_definitions_proto_rawDescGZIP(), []int{4}
}

func (x *Pareto) GetIds() *ParetoIDs {
	if x != nil {
		return x.Ids
	}
	return nil
}

func (x *Pareto) GetVectors() []*Vector {
	if x != nil {
		return x.Vectors
	}
	return nil
}

func (x *Pareto) GetMaxObjs() []float64 {
	if x != nil {
		return x.MaxObjs
	}
	return nil
}

var File_api_v1_definitions_proto protoreflect.FileDescriptor

var file_api_v1_definitions_proto_rawDesc = []byte{
	0x0a, 0x18, 0x61, 0x70, 0x69, 0x2f, 0x76, 0x31, 0x2f, 0x64, 0x65, 0x66, 0x69, 0x6e, 0x69, 0x74,
	0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06, 0x61, 0x70, 0x69, 0x2e,
	0x76, 0x31, 0x22, 0x1b, 0x0a, 0x09, 0x56, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x49, 0x44, 0x73, 0x12,
	0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x02, 0x69, 0x64, 0x22,
	0x96, 0x01, 0x0a, 0x06, 0x56, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x12, 0x23, 0x0a, 0x03, 0x69, 0x64,
	0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x76, 0x31,
	0x2e, 0x56, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x49, 0x44, 0x73, 0x52, 0x03, 0x69, 0x64, 0x73, 0x12,
	0x1a, 0x0a, 0x08, 0x65, 0x6c, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28,
	0x01, 0x52, 0x08, 0x65, 0x6c, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x12, 0x1e, 0x0a, 0x0a, 0x6f,
	0x62, 0x6a, 0x65, 0x63, 0x74, 0x69, 0x76, 0x65, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x01, 0x52,
	0x0a, 0x6f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x69, 0x76, 0x65, 0x73, 0x12, 0x2b, 0x0a, 0x11, 0x63,
	0x72, 0x6f, 0x77, 0x64, 0x69, 0x6e, 0x67, 0x5f, 0x64, 0x69, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x01, 0x52, 0x10, 0x63, 0x72, 0x6f, 0x77, 0x64, 0x69, 0x6e, 0x67,
	0x44, 0x69, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x22, 0xbd, 0x01, 0x0a, 0x14, 0x50, 0x6f, 0x70,
	0x75, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x65, 0x74, 0x65, 0x72,
	0x73, 0x12, 0x27, 0x0a, 0x0f, 0x70, 0x6f, 0x70, 0x75, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f,
	0x73, 0x69, 0x7a, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0e, 0x70, 0x6f, 0x70, 0x75,
	0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x69, 0x7a, 0x65, 0x12, 0x27, 0x0a, 0x0f, 0x64, 0x69,
	0x6d, 0x65, 0x6e, 0x73, 0x69, 0x6f, 0x6e, 0x73, 0x5f, 0x73, 0x69, 0x7a, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x0e, 0x64, 0x69, 0x6d, 0x65, 0x6e, 0x73, 0x69, 0x6f, 0x6e, 0x73, 0x53,
	0x69, 0x7a, 0x65, 0x12, 0x25, 0x0a, 0x0e, 0x6f, 0x62, 0x6a, 0x65, 0x74, 0x69, 0x76, 0x65, 0x73,
	0x5f, 0x73, 0x69, 0x7a, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0d, 0x6f, 0x62, 0x6a,
	0x65, 0x74, 0x69, 0x76, 0x65, 0x73, 0x53, 0x69, 0x7a, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x66, 0x6c,
	0x6f, 0x6f, 0x72, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x01, 0x52, 0x06, 0x66, 0x6c, 0x6f, 0x6f,
	0x72, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x63, 0x65, 0x69, 0x6c, 0x73, 0x18, 0x05, 0x20, 0x03, 0x28,
	0x01, 0x52, 0x05, 0x63, 0x65, 0x69, 0x6c, 0x73, 0x22, 0x34, 0x0a, 0x09, 0x50, 0x61, 0x72, 0x65,
	0x74, 0x6f, 0x49, 0x44, 0x73, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x04, 0x52, 0x02, 0x69, 0x64, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x22, 0x72,
	0x0a, 0x06, 0x50, 0x61, 0x72, 0x65, 0x74, 0x6f, 0x12, 0x23, 0x0a, 0x03, 0x69, 0x64, 0x73, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x76, 0x31, 0x2e, 0x50,
	0x61, 0x72, 0x65, 0x74, 0x6f, 0x49, 0x44, 0x73, 0x52, 0x03, 0x69, 0x64, 0x73, 0x12, 0x28, 0x0a,
	0x07, 0x76, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0e,
	0x2e, 0x61, 0x70, 0x69, 0x2e, 0x76, 0x31, 0x2e, 0x56, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x52, 0x07,
	0x76, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x73, 0x12, 0x19, 0x0a, 0x08, 0x6d, 0x61, 0x78, 0x5f, 0x6f,
	0x62, 0x6a, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x01, 0x52, 0x07, 0x6d, 0x61, 0x78, 0x4f, 0x62,
	0x6a, 0x73, 0x42, 0x09, 0x5a, 0x07, 0x70, 0x6b, 0x67, 0x2f, 0x61, 0x70, 0x69, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_api_v1_definitions_proto_rawDescOnce sync.Once
	file_api_v1_definitions_proto_rawDescData = file_api_v1_definitions_proto_rawDesc
)

func file_api_v1_definitions_proto_rawDescGZIP() []byte {
	file_api_v1_definitions_proto_rawDescOnce.Do(func() {
		file_api_v1_definitions_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_v1_definitions_proto_rawDescData)
	})
	return file_api_v1_definitions_proto_rawDescData
}

var file_api_v1_definitions_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_api_v1_definitions_proto_goTypes = []any{
	(*VectorIDs)(nil),            // 0: api.v1.VectorIDs
	(*Vector)(nil),               // 1: api.v1.Vector
	(*PopulationParameters)(nil), // 2: api.v1.PopulationParameters
	(*ParetoIDs)(nil),            // 3: api.v1.ParetoIDs
	(*Pareto)(nil),               // 4: api.v1.Pareto
}
var file_api_v1_definitions_proto_depIdxs = []int32{
	0, // 0: api.v1.Vector.ids:type_name -> api.v1.VectorIDs
	3, // 1: api.v1.Pareto.ids:type_name -> api.v1.ParetoIDs
	1, // 2: api.v1.Pareto.vectors:type_name -> api.v1.Vector
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_api_v1_definitions_proto_init() }
func file_api_v1_definitions_proto_init() {
	if File_api_v1_definitions_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_v1_definitions_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_v1_definitions_proto_goTypes,
		DependencyIndexes: file_api_v1_definitions_proto_depIdxs,
		MessageInfos:      file_api_v1_definitions_proto_msgTypes,
	}.Build()
	File_api_v1_definitions_proto = out.File
	file_api_v1_definitions_proto_rawDesc = nil
	file_api_v1_definitions_proto_goTypes = nil
	file_api_v1_definitions_proto_depIdxs = nil
}
