// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        (unknown)
// source: api/v1/definitions.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// VectorIDs contain identifiers for a population.
type VectorIDs struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *VectorIDs) Reset() {
	*x = VectorIDs{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_definitions_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VectorIDs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VectorIDs) ProtoMessage() {}

func (x *VectorIDs) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_definitions_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VectorIDs.ProtoReflect.Descriptor instead.
func (*VectorIDs) Descriptor() ([]byte, []int) {
	return file_api_v1_definitions_proto_rawDescGZIP(), []int{0}
}

func (x *VectorIDs) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

// Vector is an element used in the Differential Evoluition algorithm.
type Vector struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ids              *VectorIDs `protobuf:"bytes,1,opt,name=ids,proto3" json:"ids,omitempty"`
	Elements         []float64  `protobuf:"fixed64,2,rep,packed,name=elements,proto3" json:"elements,omitempty"`
	Objectives       []float64  `protobuf:"fixed64,3,rep,packed,name=objectives,proto3" json:"objectives,omitempty"`
	CrowdingDistance float64    `protobuf:"fixed64,4,opt,name=crowding_distance,json=crowdingDistance,proto3" json:"crowding_distance,omitempty"`
}

func (x *Vector) Reset() {
	*x = Vector{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_definitions_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Vector) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Vector) ProtoMessage() {}

func (x *Vector) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_definitions_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Vector.ProtoReflect.Descriptor instead.
func (*Vector) Descriptor() ([]byte, []int) {
	return file_api_v1_definitions_proto_rawDescGZIP(), []int{1}
}

func (x *Vector) GetIds() *VectorIDs {
	if x != nil {
		return x.Ids
	}
	return nil
}

func (x *Vector) GetElements() []float64 {
	if x != nil {
		return x.Elements
	}
	return nil
}

func (x *Vector) GetObjectives() []float64 {
	if x != nil {
		return x.Objectives
	}
	return nil
}

func (x *Vector) GetCrowdingDistance() float64 {
	if x != nil {
		return x.CrowdingDistance
	}
	return 0
}

// PopulationIDs contain identifiers for a population.
type PopulationIDs struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *PopulationIDs) Reset() {
	*x = PopulationIDs{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_definitions_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PopulationIDs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PopulationIDs) ProtoMessage() {}

func (x *PopulationIDs) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_definitions_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PopulationIDs.ProtoReflect.Descriptor instead.
func (*PopulationIDs) Descriptor() ([]byte, []int) {
	return file_api_v1_definitions_proto_rawDescGZIP(), []int{2}
}

func (x *PopulationIDs) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

// Population is a vector set, which describes the population of a generation in
// the evolutionary algorithm.
type Population struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ids     *PopulationIDs `protobuf:"bytes,1,opt,name=ids,proto3" json:"ids,omitempty"`
	Vectors []*Vector      `protobuf:"bytes,2,rep,name=vectors,proto3" json:"vectors,omitempty"`
}

func (x *Population) Reset() {
	*x = Population{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_definitions_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Population) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Population) ProtoMessage() {}

func (x *Population) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_definitions_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Population.ProtoReflect.Descriptor instead.
func (*Population) Descriptor() ([]byte, []int) {
	return file_api_v1_definitions_proto_rawDescGZIP(), []int{3}
}

func (x *Population) GetIds() *PopulationIDs {
	if x != nil {
		return x.Ids
	}
	return nil
}

func (x *Population) GetVectors() []*Vector {
	if x != nil {
		return x.Vectors
	}
	return nil
}

// PopulationParameters are the values used by a Population in a generation.
type PopulationParameters struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PopulationSize int64     `protobuf:"varint,1,opt,name=population_size,json=populationSize,proto3" json:"population_size,omitempty"`
	DimensionsSize int64     `protobuf:"varint,2,opt,name=dimensions_size,json=dimensionsSize,proto3" json:"dimensions_size,omitempty"`
	ObjetivesSize  int64     `protobuf:"varint,3,opt,name=objetives_size,json=objetivesSize,proto3" json:"objetives_size,omitempty"`
	Floors         []float64 `protobuf:"fixed64,4,rep,packed,name=floors,proto3" json:"floors,omitempty"`
	Ceils          []float64 `protobuf:"fixed64,5,rep,packed,name=ceils,proto3" json:"ceils,omitempty"`
}

func (x *PopulationParameters) Reset() {
	*x = PopulationParameters{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_definitions_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PopulationParameters) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PopulationParameters) ProtoMessage() {}

func (x *PopulationParameters) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_definitions_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PopulationParameters.ProtoReflect.Descriptor instead.
func (*PopulationParameters) Descriptor() ([]byte, []int) {
	return file_api_v1_definitions_proto_rawDescGZIP(), []int{4}
}

func (x *PopulationParameters) GetPopulationSize() int64 {
	if x != nil {
		return x.PopulationSize
	}
	return 0
}

func (x *PopulationParameters) GetDimensionsSize() int64 {
	if x != nil {
		return x.DimensionsSize
	}
	return 0
}

func (x *PopulationParameters) GetObjetivesSize() int64 {
	if x != nil {
		return x.ObjetivesSize
	}
	return 0
}

func (x *PopulationParameters) GetFloors() []float64 {
	if x != nil {
		return x.Floors
	}
	return nil
}

func (x *PopulationParameters) GetCeils() []float64 {
	if x != nil {
		return x.Ceils
	}
	return nil
}

// GenerationIDs contain identifiers for a Generation.
type GenerationIDs struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *GenerationIDs) Reset() {
	*x = GenerationIDs{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_definitions_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GenerationIDs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerationIDs) ProtoMessage() {}

func (x *GenerationIDs) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_definitions_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerationIDs.ProtoReflect.Descriptor instead.
func (*GenerationIDs) Descriptor() ([]byte, []int) {
	return file_api_v1_definitions_proto_rawDescGZIP(), []int{5}
}

func (x *GenerationIDs) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

// Generation is a steps on the Differential Evolution algorithm, each
// generation a new population is generated via mutation and filtered according
// to their performance in the problem.
type Generation struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ids         *GenerationIDs `protobuf:"bytes,1,opt,name=ids,proto3" json:"ids,omitempty"`
	ExecutionId uint64         `protobuf:"varint,2,opt,name=execution_id,json=executionId,proto3" json:"execution_id,omitempty"`
	Populations []*Population  `protobuf:"bytes,3,rep,name=populations,proto3" json:"populations,omitempty"`
}

func (x *Generation) Reset() {
	*x = Generation{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_definitions_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Generation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Generation) ProtoMessage() {}

func (x *Generation) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_definitions_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Generation.ProtoReflect.Descriptor instead.
func (*Generation) Descriptor() ([]byte, []int) {
	return file_api_v1_definitions_proto_rawDescGZIP(), []int{6}
}

func (x *Generation) GetIds() *GenerationIDs {
	if x != nil {
		return x.Ids
	}
	return nil
}

func (x *Generation) GetExecutionId() uint64 {
	if x != nil {
		return x.ExecutionId
	}
	return 0
}

func (x *Generation) GetPopulations() []*Population {
	if x != nil {
		return x.Populations
	}
	return nil
}

type ParetoIDs struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id     uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId string `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
}

func (x *ParetoIDs) Reset() {
	*x = ParetoIDs{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_definitions_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ParetoIDs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ParetoIDs) ProtoMessage() {}

func (x *ParetoIDs) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_definitions_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ParetoIDs.ProtoReflect.Descriptor instead.
func (*ParetoIDs) Descriptor() ([]byte, []int) {
	return file_api_v1_definitions_proto_rawDescGZIP(), []int{7}
}

func (x *ParetoIDs) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ParetoIDs) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type Pareto struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ids        *ParetoIDs  `protobuf:"bytes,1,opt,name=ids,proto3" json:"ids,omitempty"`
	Population *Population `protobuf:"bytes,2,opt,name=population,proto3" json:"population,omitempty"`
	MaxObjs    []float64   `protobuf:"fixed64,3,rep,packed,name=max_objs,json=maxObjs,proto3" json:"max_objs,omitempty"`
}

func (x *Pareto) Reset() {
	*x = Pareto{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_definitions_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Pareto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Pareto) ProtoMessage() {}

func (x *Pareto) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_definitions_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Pareto.ProtoReflect.Descriptor instead.
func (*Pareto) Descriptor() ([]byte, []int) {
	return file_api_v1_definitions_proto_rawDescGZIP(), []int{8}
}

func (x *Pareto) GetIds() *ParetoIDs {
	if x != nil {
		return x.Ids
	}
	return nil
}

func (x *Pareto) GetPopulation() *Population {
	if x != nil {
		return x.Population
	}
	return nil
}

func (x *Pareto) GetMaxObjs() []float64 {
	if x != nil {
		return x.MaxObjs
	}
	return nil
}

var File_api_v1_definitions_proto protoreflect.FileDescriptor

var file_api_v1_definitions_proto_rawDesc = []byte{
	0x0a, 0x18, 0x61, 0x70, 0x69, 0x2f, 0x76, 0x31, 0x2f, 0x64, 0x65, 0x66, 0x69, 0x6e, 0x69, 0x74,
	0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06, 0x61, 0x70, 0x69, 0x2e,
	0x76, 0x31, 0x22, 0x1b, 0x0a, 0x09, 0x56, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x49, 0x44, 0x73, 0x12,
	0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x02, 0x69, 0x64, 0x22,
	0x96, 0x01, 0x0a, 0x06, 0x56, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x12, 0x23, 0x0a, 0x03, 0x69, 0x64,
	0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x76, 0x31,
	0x2e, 0x56, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x49, 0x44, 0x73, 0x52, 0x03, 0x69, 0x64, 0x73, 0x12,
	0x1a, 0x0a, 0x08, 0x65, 0x6c, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28,
	0x01, 0x52, 0x08, 0x65, 0x6c, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x12, 0x1e, 0x0a, 0x0a, 0x6f,
	0x62, 0x6a, 0x65, 0x63, 0x74, 0x69, 0x76, 0x65, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x01, 0x52,
	0x0a, 0x6f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x69, 0x76, 0x65, 0x73, 0x12, 0x2b, 0x0a, 0x11, 0x63,
	0x72, 0x6f, 0x77, 0x64, 0x69, 0x6e, 0x67, 0x5f, 0x64, 0x69, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x01, 0x52, 0x10, 0x63, 0x72, 0x6f, 0x77, 0x64, 0x69, 0x6e, 0x67,
	0x44, 0x69, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x22, 0x1f, 0x0a, 0x0d, 0x50, 0x6f, 0x70, 0x75,
	0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x44, 0x73, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x02, 0x69, 0x64, 0x22, 0x5f, 0x0a, 0x0a, 0x50, 0x6f, 0x70,
	0x75, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x27, 0x0a, 0x03, 0x69, 0x64, 0x73, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x76, 0x31, 0x2e, 0x50, 0x6f,
	0x70, 0x75, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x44, 0x73, 0x52, 0x03, 0x69, 0x64, 0x73,
	0x12, 0x28, 0x0a, 0x07, 0x76, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x0e, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x76, 0x31, 0x2e, 0x56, 0x65, 0x63, 0x74, 0x6f,
	0x72, 0x52, 0x07, 0x76, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x73, 0x22, 0xbd, 0x01, 0x0a, 0x14, 0x50,
	0x6f, 0x70, 0x75, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x65, 0x74,
	0x65, 0x72, 0x73, 0x12, 0x27, 0x0a, 0x0f, 0x70, 0x6f, 0x70, 0x75, 0x6c, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x5f, 0x73, 0x69, 0x7a, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0e, 0x70, 0x6f,
	0x70, 0x75, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x69, 0x7a, 0x65, 0x12, 0x27, 0x0a, 0x0f,
	0x64, 0x69, 0x6d, 0x65, 0x6e, 0x73, 0x69, 0x6f, 0x6e, 0x73, 0x5f, 0x73, 0x69, 0x7a, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0e, 0x64, 0x69, 0x6d, 0x65, 0x6e, 0x73, 0x69, 0x6f, 0x6e,
	0x73, 0x53, 0x69, 0x7a, 0x65, 0x12, 0x25, 0x0a, 0x0e, 0x6f, 0x62, 0x6a, 0x65, 0x74, 0x69, 0x76,
	0x65, 0x73, 0x5f, 0x73, 0x69, 0x7a, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0d, 0x6f,
	0x62, 0x6a, 0x65, 0x74, 0x69, 0x76, 0x65, 0x73, 0x53, 0x69, 0x7a, 0x65, 0x12, 0x16, 0x0a, 0x06,
	0x66, 0x6c, 0x6f, 0x6f, 0x72, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x01, 0x52, 0x06, 0x66, 0x6c,
	0x6f, 0x6f, 0x72, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x63, 0x65, 0x69, 0x6c, 0x73, 0x18, 0x05, 0x20,
	0x03, 0x28, 0x01, 0x52, 0x05, 0x63, 0x65, 0x69, 0x6c, 0x73, 0x22, 0x1f, 0x0a, 0x0d, 0x47, 0x65,
	0x6e, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x44, 0x73, 0x12, 0x0e, 0x0a, 0x02, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x02, 0x69, 0x64, 0x22, 0x8e, 0x01, 0x0a, 0x0a,
	0x47, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x27, 0x0a, 0x03, 0x69, 0x64,
	0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x76, 0x31,
	0x2e, 0x47, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x44, 0x73, 0x52, 0x03,
	0x69, 0x64, 0x73, 0x12, 0x21, 0x0a, 0x0c, 0x65, 0x78, 0x65, 0x63, 0x75, 0x74, 0x69, 0x6f, 0x6e,
	0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0b, 0x65, 0x78, 0x65, 0x63, 0x75,
	0x74, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x12, 0x34, 0x0a, 0x0b, 0x70, 0x6f, 0x70, 0x75, 0x6c, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x61, 0x70,
	0x69, 0x2e, 0x76, 0x31, 0x2e, 0x50, 0x6f, 0x70, 0x75, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52,
	0x0b, 0x70, 0x6f, 0x70, 0x75, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x22, 0x34, 0x0a, 0x09,
	0x50, 0x61, 0x72, 0x65, 0x74, 0x6f, 0x49, 0x44, 0x73, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x02, 0x69, 0x64, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65,
	0x72, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72,
	0x49, 0x64, 0x22, 0x7c, 0x0a, 0x06, 0x50, 0x61, 0x72, 0x65, 0x74, 0x6f, 0x12, 0x23, 0x0a, 0x03,
	0x69, 0x64, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x61, 0x70, 0x69, 0x2e,
	0x76, 0x31, 0x2e, 0x50, 0x61, 0x72, 0x65, 0x74, 0x6f, 0x49, 0x44, 0x73, 0x52, 0x03, 0x69, 0x64,
	0x73, 0x12, 0x32, 0x0a, 0x0a, 0x70, 0x6f, 0x70, 0x75, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x76, 0x31, 0x2e, 0x50,
	0x6f, 0x70, 0x75, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x0a, 0x70, 0x6f, 0x70, 0x75, 0x6c,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x19, 0x0a, 0x08, 0x6d, 0x61, 0x78, 0x5f, 0x6f, 0x62, 0x6a,
	0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x01, 0x52, 0x07, 0x6d, 0x61, 0x78, 0x4f, 0x62, 0x6a, 0x73,
	0x42, 0x09, 0x5a, 0x07, 0x70, 0x6b, 0x67, 0x2f, 0x61, 0x70, 0x69, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_api_v1_definitions_proto_rawDescOnce sync.Once
	file_api_v1_definitions_proto_rawDescData = file_api_v1_definitions_proto_rawDesc
)

func file_api_v1_definitions_proto_rawDescGZIP() []byte {
	file_api_v1_definitions_proto_rawDescOnce.Do(func() {
		file_api_v1_definitions_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_v1_definitions_proto_rawDescData)
	})
	return file_api_v1_definitions_proto_rawDescData
}

var file_api_v1_definitions_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_api_v1_definitions_proto_goTypes = []interface{}{
	(*VectorIDs)(nil),            // 0: api.v1.VectorIDs
	(*Vector)(nil),               // 1: api.v1.Vector
	(*PopulationIDs)(nil),        // 2: api.v1.PopulationIDs
	(*Population)(nil),           // 3: api.v1.Population
	(*PopulationParameters)(nil), // 4: api.v1.PopulationParameters
	(*GenerationIDs)(nil),        // 5: api.v1.GenerationIDs
	(*Generation)(nil),           // 6: api.v1.Generation
	(*ParetoIDs)(nil),            // 7: api.v1.ParetoIDs
	(*Pareto)(nil),               // 8: api.v1.Pareto
}
var file_api_v1_definitions_proto_depIdxs = []int32{
	0, // 0: api.v1.Vector.ids:type_name -> api.v1.VectorIDs
	2, // 1: api.v1.Population.ids:type_name -> api.v1.PopulationIDs
	1, // 2: api.v1.Population.vectors:type_name -> api.v1.Vector
	5, // 3: api.v1.Generation.ids:type_name -> api.v1.GenerationIDs
	3, // 4: api.v1.Generation.populations:type_name -> api.v1.Population
	7, // 5: api.v1.Pareto.ids:type_name -> api.v1.ParetoIDs
	3, // 6: api.v1.Pareto.population:type_name -> api.v1.Population
	7, // [7:7] is the sub-list for method output_type
	7, // [7:7] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_api_v1_definitions_proto_init() }
func file_api_v1_definitions_proto_init() {
	if File_api_v1_definitions_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_v1_definitions_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VectorIDs); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1_definitions_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Vector); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1_definitions_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PopulationIDs); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1_definitions_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Population); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1_definitions_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PopulationParameters); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1_definitions_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GenerationIDs); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1_definitions_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Generation); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1_definitions_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ParetoIDs); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1_definitions_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Pareto); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_v1_definitions_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_v1_definitions_proto_goTypes,
		DependencyIndexes: file_api_v1_definitions_proto_depIdxs,
		MessageInfos:      file_api_v1_definitions_proto_msgTypes,
	}.Build()
	File_api_v1_definitions_proto = out.File
	file_api_v1_definitions_proto_rawDesc = nil
	file_api_v1_definitions_proto_goTypes = nil
	file_api_v1_definitions_proto_depIdxs = nil
}
