// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: api/v1/differential_evolution.proto

package api

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	DifferentialEvolutionService_ListSupportedAlgorithms_FullMethodName = "/api.v1.DifferentialEvolutionService/ListSupportedAlgorithms"
	DifferentialEvolutionService_ListSupportedVariants_FullMethodName   = "/api.v1.DifferentialEvolutionService/ListSupportedVariants"
	DifferentialEvolutionService_ListSupportedProblems_FullMethodName   = "/api.v1.DifferentialEvolutionService/ListSupportedProblems"
	DifferentialEvolutionService_RunAsync_FullMethodName                = "/api.v1.DifferentialEvolutionService/RunAsync"
	DifferentialEvolutionService_StreamProgress_FullMethodName          = "/api.v1.DifferentialEvolutionService/StreamProgress"
	DifferentialEvolutionService_GetExecutionStatus_FullMethodName      = "/api.v1.DifferentialEvolutionService/GetExecutionStatus"
	DifferentialEvolutionService_GetExecutionResults_FullMethodName     = "/api.v1.DifferentialEvolutionService/GetExecutionResults"
	DifferentialEvolutionService_ListExecutions_FullMethodName          = "/api.v1.DifferentialEvolutionService/ListExecutions"
	DifferentialEvolutionService_CancelExecution_FullMethodName         = "/api.v1.DifferentialEvolutionService/CancelExecution"
	DifferentialEvolutionService_DeleteExecution_FullMethodName         = "/api.v1.DifferentialEvolutionService/DeleteExecution"
)

// DifferentialEvolutionServiceClient is the client API for DifferentialEvolutionService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DifferentialEvolutionServiceClient interface {
	ListSupportedAlgorithms(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*ListSupportedAlgorithmsResponse, error)
	ListSupportedVariants(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*ListSupportedVariantsResponse, error)
	ListSupportedProblems(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*ListSupportedProblemsResponse, error)
	// Async execution RPCs
	RunAsync(ctx context.Context, in *RunAsyncRequest, opts ...grpc.CallOption) (*RunAsyncResponse, error)
	StreamProgress(ctx context.Context, in *StreamProgressRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[StreamProgressResponse], error)
	GetExecutionStatus(ctx context.Context, in *GetExecutionStatusRequest, opts ...grpc.CallOption) (*GetExecutionStatusResponse, error)
	GetExecutionResults(ctx context.Context, in *GetExecutionResultsRequest, opts ...grpc.CallOption) (*GetExecutionResultsResponse, error)
	ListExecutions(ctx context.Context, in *ListExecutionsRequest, opts ...grpc.CallOption) (*ListExecutionsResponse, error)
	CancelExecution(ctx context.Context, in *CancelExecutionRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	DeleteExecution(ctx context.Context, in *DeleteExecutionRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type differentialEvolutionServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDifferentialEvolutionServiceClient(cc grpc.ClientConnInterface) DifferentialEvolutionServiceClient {
	return &differentialEvolutionServiceClient{cc}
}

func (c *differentialEvolutionServiceClient) ListSupportedAlgorithms(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*ListSupportedAlgorithmsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListSupportedAlgorithmsResponse)
	err := c.cc.Invoke(ctx, DifferentialEvolutionService_ListSupportedAlgorithms_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *differentialEvolutionServiceClient) ListSupportedVariants(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*ListSupportedVariantsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListSupportedVariantsResponse)
	err := c.cc.Invoke(ctx, DifferentialEvolutionService_ListSupportedVariants_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *differentialEvolutionServiceClient) ListSupportedProblems(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*ListSupportedProblemsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListSupportedProblemsResponse)
	err := c.cc.Invoke(ctx, DifferentialEvolutionService_ListSupportedProblems_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *differentialEvolutionServiceClient) RunAsync(ctx context.Context, in *RunAsyncRequest, opts ...grpc.CallOption) (*RunAsyncResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RunAsyncResponse)
	err := c.cc.Invoke(ctx, DifferentialEvolutionService_RunAsync_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *differentialEvolutionServiceClient) StreamProgress(ctx context.Context, in *StreamProgressRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[StreamProgressResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &DifferentialEvolutionService_ServiceDesc.Streams[0], DifferentialEvolutionService_StreamProgress_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[StreamProgressRequest, StreamProgressResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DifferentialEvolutionService_StreamProgressClient = grpc.ServerStreamingClient[StreamProgressResponse]

func (c *differentialEvolutionServiceClient) GetExecutionStatus(ctx context.Context, in *GetExecutionStatusRequest, opts ...grpc.CallOption) (*GetExecutionStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetExecutionStatusResponse)
	err := c.cc.Invoke(ctx, DifferentialEvolutionService_GetExecutionStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *differentialEvolutionServiceClient) GetExecutionResults(ctx context.Context, in *GetExecutionResultsRequest, opts ...grpc.CallOption) (*GetExecutionResultsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetExecutionResultsResponse)
	err := c.cc.Invoke(ctx, DifferentialEvolutionService_GetExecutionResults_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *differentialEvolutionServiceClient) ListExecutions(ctx context.Context, in *ListExecutionsRequest, opts ...grpc.CallOption) (*ListExecutionsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListExecutionsResponse)
	err := c.cc.Invoke(ctx, DifferentialEvolutionService_ListExecutions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *differentialEvolutionServiceClient) CancelExecution(ctx context.Context, in *CancelExecutionRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, DifferentialEvolutionService_CancelExecution_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *differentialEvolutionServiceClient) DeleteExecution(ctx context.Context, in *DeleteExecutionRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, DifferentialEvolutionService_DeleteExecution_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DifferentialEvolutionServiceServer is the server API for DifferentialEvolutionService service.
// All implementations must embed UnimplementedDifferentialEvolutionServiceServer
// for forward compatibility.
type DifferentialEvolutionServiceServer interface {
	ListSupportedAlgorithms(context.Context, *emptypb.Empty) (*ListSupportedAlgorithmsResponse, error)
	ListSupportedVariants(context.Context, *emptypb.Empty) (*ListSupportedVariantsResponse, error)
	ListSupportedProblems(context.Context, *emptypb.Empty) (*ListSupportedProblemsResponse, error)
	// Async execution RPCs
	RunAsync(context.Context, *RunAsyncRequest) (*RunAsyncResponse, error)
	StreamProgress(*StreamProgressRequest, grpc.ServerStreamingServer[StreamProgressResponse]) error
	GetExecutionStatus(context.Context, *GetExecutionStatusRequest) (*GetExecutionStatusResponse, error)
	GetExecutionResults(context.Context, *GetExecutionResultsRequest) (*GetExecutionResultsResponse, error)
	ListExecutions(context.Context, *ListExecutionsRequest) (*ListExecutionsResponse, error)
	CancelExecution(context.Context, *CancelExecutionRequest) (*emptypb.Empty, error)
	DeleteExecution(context.Context, *DeleteExecutionRequest) (*emptypb.Empty, error)
	mustEmbedUnimplementedDifferentialEvolutionServiceServer()
}

// UnimplementedDifferentialEvolutionServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDifferentialEvolutionServiceServer struct{}

func (UnimplementedDifferentialEvolutionServiceServer) ListSupportedAlgorithms(context.Context, *emptypb.Empty) (*ListSupportedAlgorithmsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListSupportedAlgorithms not implemented")
}
func (UnimplementedDifferentialEvolutionServiceServer) ListSupportedVariants(context.Context, *emptypb.Empty) (*ListSupportedVariantsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListSupportedVariants not implemented")
}
func (UnimplementedDifferentialEvolutionServiceServer) ListSupportedProblems(context.Context, *emptypb.Empty) (*ListSupportedProblemsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListSupportedProblems not implemented")
}
func (UnimplementedDifferentialEvolutionServiceServer) RunAsync(context.Context, *RunAsyncRequest) (*RunAsyncResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RunAsync not implemented")
}
func (UnimplementedDifferentialEvolutionServiceServer) StreamProgress(*StreamProgressRequest, grpc.ServerStreamingServer[StreamProgressResponse]) error {
	return status.Errorf(codes.Unimplemented, "method StreamProgress not implemented")
}
func (UnimplementedDifferentialEvolutionServiceServer) GetExecutionStatus(context.Context, *GetExecutionStatusRequest) (*GetExecutionStatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetExecutionStatus not implemented")
}
func (UnimplementedDifferentialEvolutionServiceServer) GetExecutionResults(context.Context, *GetExecutionResultsRequest) (*GetExecutionResultsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetExecutionResults not implemented")
}
func (UnimplementedDifferentialEvolutionServiceServer) ListExecutions(context.Context, *ListExecutionsRequest) (*ListExecutionsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListExecutions not implemented")
}
func (UnimplementedDifferentialEvolutionServiceServer) CancelExecution(context.Context, *CancelExecutionRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CancelExecution not implemented")
}
func (UnimplementedDifferentialEvolutionServiceServer) DeleteExecution(context.Context, *DeleteExecutionRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteExecution not implemented")
}
func (UnimplementedDifferentialEvolutionServiceServer) mustEmbedUnimplementedDifferentialEvolutionServiceServer() {
}
func (UnimplementedDifferentialEvolutionServiceServer) testEmbeddedByValue() {}

// UnsafeDifferentialEvolutionServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DifferentialEvolutionServiceServer will
// result in compilation errors.
type UnsafeDifferentialEvolutionServiceServer interface {
	mustEmbedUnimplementedDifferentialEvolutionServiceServer()
}

func RegisterDifferentialEvolutionServiceServer(s grpc.ServiceRegistrar, srv DifferentialEvolutionServiceServer) {
	// If the following call pancis, it indicates UnimplementedDifferentialEvolutionServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DifferentialEvolutionService_ServiceDesc, srv)
}

func _DifferentialEvolutionService_ListSupportedAlgorithms_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DifferentialEvolutionServiceServer).ListSupportedAlgorithms(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DifferentialEvolutionService_ListSupportedAlgorithms_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DifferentialEvolutionServiceServer).ListSupportedAlgorithms(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _DifferentialEvolutionService_ListSupportedVariants_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DifferentialEvolutionServiceServer).ListSupportedVariants(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DifferentialEvolutionService_ListSupportedVariants_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DifferentialEvolutionServiceServer).ListSupportedVariants(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _DifferentialEvolutionService_ListSupportedProblems_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DifferentialEvolutionServiceServer).ListSupportedProblems(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DifferentialEvolutionService_ListSupportedProblems_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DifferentialEvolutionServiceServer).ListSupportedProblems(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _DifferentialEvolutionService_RunAsync_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RunAsyncRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DifferentialEvolutionServiceServer).RunAsync(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DifferentialEvolutionService_RunAsync_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DifferentialEvolutionServiceServer).RunAsync(ctx, req.(*RunAsyncRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DifferentialEvolutionService_StreamProgress_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StreamProgressRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(DifferentialEvolutionServiceServer).StreamProgress(m, &grpc.GenericServerStream[StreamProgressRequest, StreamProgressResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DifferentialEvolutionService_StreamProgressServer = grpc.ServerStreamingServer[StreamProgressResponse]

func _DifferentialEvolutionService_GetExecutionStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetExecutionStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DifferentialEvolutionServiceServer).GetExecutionStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DifferentialEvolutionService_GetExecutionStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DifferentialEvolutionServiceServer).GetExecutionStatus(ctx, req.(*GetExecutionStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DifferentialEvolutionService_GetExecutionResults_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetExecutionResultsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DifferentialEvolutionServiceServer).GetExecutionResults(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DifferentialEvolutionService_GetExecutionResults_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DifferentialEvolutionServiceServer).GetExecutionResults(ctx, req.(*GetExecutionResultsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DifferentialEvolutionService_ListExecutions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListExecutionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DifferentialEvolutionServiceServer).ListExecutions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DifferentialEvolutionService_ListExecutions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DifferentialEvolutionServiceServer).ListExecutions(ctx, req.(*ListExecutionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DifferentialEvolutionService_CancelExecution_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CancelExecutionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DifferentialEvolutionServiceServer).CancelExecution(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DifferentialEvolutionService_CancelExecution_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DifferentialEvolutionServiceServer).CancelExecution(ctx, req.(*CancelExecutionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DifferentialEvolutionService_DeleteExecution_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteExecutionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DifferentialEvolutionServiceServer).DeleteExecution(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DifferentialEvolutionService_DeleteExecution_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DifferentialEvolutionServiceServer).DeleteExecution(ctx, req.(*DeleteExecutionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// DifferentialEvolutionService_ServiceDesc is the grpc.ServiceDesc for DifferentialEvolutionService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DifferentialEvolutionService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.v1.DifferentialEvolutionService",
	HandlerType: (*DifferentialEvolutionServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListSupportedAlgorithms",
			Handler:    _DifferentialEvolutionService_ListSupportedAlgorithms_Handler,
		},
		{
			MethodName: "ListSupportedVariants",
			Handler:    _DifferentialEvolutionService_ListSupportedVariants_Handler,
		},
		{
			MethodName: "ListSupportedProblems",
			Handler:    _DifferentialEvolutionService_ListSupportedProblems_Handler,
		},
		{
			MethodName: "RunAsync",
			Handler:    _DifferentialEvolutionService_RunAsync_Handler,
		},
		{
			MethodName: "GetExecutionStatus",
			Handler:    _DifferentialEvolutionService_GetExecutionStatus_Handler,
		},
		{
			MethodName: "GetExecutionResults",
			Handler:    _DifferentialEvolutionService_GetExecutionResults_Handler,
		},
		{
			MethodName: "ListExecutions",
			Handler:    _DifferentialEvolutionService_ListExecutions_Handler,
		},
		{
			MethodName: "CancelExecution",
			Handler:    _DifferentialEvolutionService_CancelExecution_Handler,
		},
		{
			MethodName: "DeleteExecution",
			Handler:    _DifferentialEvolutionService_DeleteExecution_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamProgress",
			Handler:       _DifferentialEvolutionService_StreamProgress_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "api/v1/differential_evolution.proto",
}
