// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.21.5
// source: api/v1/differential_evolution.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Vector struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Elements         []float64 `protobuf:"fixed64,1,rep,packed,name=elements,proto3" json:"elements,omitempty"`
	Objectives       []float64 `protobuf:"fixed64,2,rep,packed,name=objectives,proto3" json:"objectives,omitempty"`
	CrowdingDistance float64   `protobuf:"fixed64,3,opt,name=crowding_distance,json=crowdingDistance,proto3" json:"crowding_distance,omitempty"`
}

func (x *Vector) Reset() {
	*x = Vector{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_differential_evolution_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Vector) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Vector) ProtoMessage() {}

func (x *Vector) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_differential_evolution_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Vector.ProtoReflect.Descriptor instead.
func (*Vector) Descriptor() ([]byte, []int) {
	return file_api_v1_differential_evolution_proto_rawDescGZIP(), []int{0}
}

func (x *Vector) GetElements() []float64 {
	if x != nil {
		return x.Elements
	}
	return nil
}

func (x *Vector) GetObjectives() []float64 {
	if x != nil {
		return x.Objectives
	}
	return nil
}

func (x *Vector) GetCrowdingDistance() float64 {
	if x != nil {
		return x.CrowdingDistance
	}
	return 0
}

type Population struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Vectors []*Vector `protobuf:"bytes,1,rep,name=vectors,proto3" json:"vectors,omitempty"`
}

func (x *Population) Reset() {
	*x = Population{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_differential_evolution_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Population) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Population) ProtoMessage() {}

func (x *Population) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_differential_evolution_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Population.ProtoReflect.Descriptor instead.
func (*Population) Descriptor() ([]byte, []int) {
	return file_api_v1_differential_evolution_proto_rawDescGZIP(), []int{1}
}

func (x *Population) GetVectors() []*Vector {
	if x != nil {
		return x.Vectors
	}
	return nil
}

type PopulationParameters struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DimensionsSize int64     `protobuf:"varint,1,opt,name=dimensions_size,json=dimensionsSize,proto3" json:"dimensions_size,omitempty"`
	ObjetivesSize  int64     `protobuf:"varint,2,opt,name=objetives_size,json=objetivesSize,proto3" json:"objetives_size,omitempty"`
	FloorSlice     []float64 `protobuf:"fixed64,3,rep,packed,name=floor_slice,json=floorSlice,proto3" json:"floor_slice,omitempty"`
	CeilSlice      []float64 `protobuf:"fixed64,4,rep,packed,name=ceil_slice,json=ceilSlice,proto3" json:"ceil_slice,omitempty"`
}

func (x *PopulationParameters) Reset() {
	*x = PopulationParameters{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_differential_evolution_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PopulationParameters) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PopulationParameters) ProtoMessage() {}

func (x *PopulationParameters) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_differential_evolution_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PopulationParameters.ProtoReflect.Descriptor instead.
func (*PopulationParameters) Descriptor() ([]byte, []int) {
	return file_api_v1_differential_evolution_proto_rawDescGZIP(), []int{2}
}

func (x *PopulationParameters) GetDimensionsSize() int64 {
	if x != nil {
		return x.DimensionsSize
	}
	return 0
}

func (x *PopulationParameters) GetObjetivesSize() int64 {
	if x != nil {
		return x.ObjetivesSize
	}
	return 0
}

func (x *PopulationParameters) GetFloorSlice() []float64 {
	if x != nil {
		return x.FloorSlice
	}
	return nil
}

func (x *PopulationParameters) GetCeilSlice() []float64 {
	if x != nil {
		return x.CeilSlice
	}
	return nil
}

type ExecutionRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ExecutionRequest) Reset() {
	*x = ExecutionRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_differential_evolution_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ExecutionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecutionRequest) ProtoMessage() {}

func (x *ExecutionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_differential_evolution_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecutionRequest.ProtoReflect.Descriptor instead.
func (*ExecutionRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_differential_evolution_proto_rawDescGZIP(), []int{3}
}

type ExecutionReponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ExecutionReponse) Reset() {
	*x = ExecutionReponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_differential_evolution_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ExecutionReponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecutionReponse) ProtoMessage() {}

func (x *ExecutionReponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_differential_evolution_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecutionReponse.ProtoReflect.Descriptor instead.
func (*ExecutionReponse) Descriptor() ([]byte, []int) {
	return file_api_v1_differential_evolution_proto_rawDescGZIP(), []int{4}
}

type MultipleExecutionsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *MultipleExecutionsRequest) Reset() {
	*x = MultipleExecutionsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_differential_evolution_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MultipleExecutionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MultipleExecutionsRequest) ProtoMessage() {}

func (x *MultipleExecutionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_differential_evolution_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MultipleExecutionsRequest.ProtoReflect.Descriptor instead.
func (*MultipleExecutionsRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_differential_evolution_proto_rawDescGZIP(), []int{5}
}

type MultipleExecutionsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *MultipleExecutionsResponse) Reset() {
	*x = MultipleExecutionsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_differential_evolution_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MultipleExecutionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MultipleExecutionsResponse) ProtoMessage() {}

func (x *MultipleExecutionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_differential_evolution_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MultipleExecutionsResponse.ProtoReflect.Descriptor instead.
func (*MultipleExecutionsResponse) Descriptor() ([]byte, []int) {
	return file_api_v1_differential_evolution_proto_rawDescGZIP(), []int{6}
}

var File_api_v1_differential_evolution_proto protoreflect.FileDescriptor

var file_api_v1_differential_evolution_proto_rawDesc = []byte{
	0x0a, 0x23, 0x61, 0x70, 0x69, 0x2f, 0x76, 0x31, 0x2f, 0x64, 0x69, 0x66, 0x66, 0x65, 0x72, 0x65,
	0x6e, 0x74, 0x69, 0x61, 0x6c, 0x5f, 0x65, 0x76, 0x6f, 0x6c, 0x75, 0x74, 0x69, 0x6f, 0x6e, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06, 0x61, 0x70, 0x69, 0x2e, 0x76, 0x31, 0x22, 0x71, 0x0a,
	0x06, 0x56, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x12, 0x1a, 0x0a, 0x08, 0x65, 0x6c, 0x65, 0x6d, 0x65,
	0x6e, 0x74, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x01, 0x52, 0x08, 0x65, 0x6c, 0x65, 0x6d, 0x65,
	0x6e, 0x74, 0x73, 0x12, 0x1e, 0x0a, 0x0a, 0x6f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x69, 0x76, 0x65,
	0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x01, 0x52, 0x0a, 0x6f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x69,
	0x76, 0x65, 0x73, 0x12, 0x2b, 0x0a, 0x11, 0x63, 0x72, 0x6f, 0x77, 0x64, 0x69, 0x6e, 0x67, 0x5f,
	0x64, 0x69, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x01, 0x52, 0x10,
	0x63, 0x72, 0x6f, 0x77, 0x64, 0x69, 0x6e, 0x67, 0x44, 0x69, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65,
	0x22, 0x36, 0x0a, 0x0a, 0x50, 0x6f, 0x70, 0x75, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x28,
	0x0a, 0x07, 0x76, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x0e, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x76, 0x31, 0x2e, 0x56, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x52,
	0x07, 0x76, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x73, 0x22, 0xa6, 0x01, 0x0a, 0x14, 0x50, 0x6f, 0x70,
	0x75, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x65, 0x74, 0x65, 0x72,
	0x73, 0x12, 0x27, 0x0a, 0x0f, 0x64, 0x69, 0x6d, 0x65, 0x6e, 0x73, 0x69, 0x6f, 0x6e, 0x73, 0x5f,
	0x73, 0x69, 0x7a, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0e, 0x64, 0x69, 0x6d, 0x65,
	0x6e, 0x73, 0x69, 0x6f, 0x6e, 0x73, 0x53, 0x69, 0x7a, 0x65, 0x12, 0x25, 0x0a, 0x0e, 0x6f, 0x62,
	0x6a, 0x65, 0x74, 0x69, 0x76, 0x65, 0x73, 0x5f, 0x73, 0x69, 0x7a, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x0d, 0x6f, 0x62, 0x6a, 0x65, 0x74, 0x69, 0x76, 0x65, 0x73, 0x53, 0x69, 0x7a,
	0x65, 0x12, 0x1f, 0x0a, 0x0b, 0x66, 0x6c, 0x6f, 0x6f, 0x72, 0x5f, 0x73, 0x6c, 0x69, 0x63, 0x65,
	0x18, 0x03, 0x20, 0x03, 0x28, 0x01, 0x52, 0x0a, 0x66, 0x6c, 0x6f, 0x6f, 0x72, 0x53, 0x6c, 0x69,
	0x63, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x63, 0x65, 0x69, 0x6c, 0x5f, 0x73, 0x6c, 0x69, 0x63, 0x65,
	0x18, 0x04, 0x20, 0x03, 0x28, 0x01, 0x52, 0x09, 0x63, 0x65, 0x69, 0x6c, 0x53, 0x6c, 0x69, 0x63,
	0x65, 0x22, 0x12, 0x0a, 0x10, 0x45, 0x78, 0x65, 0x63, 0x75, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x12, 0x0a, 0x10, 0x45, 0x78, 0x65, 0x63, 0x75, 0x74, 0x69,
	0x6f, 0x6e, 0x52, 0x65, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x1b, 0x0a, 0x19, 0x4d, 0x75, 0x6c,
	0x74, 0x69, 0x70, 0x6c, 0x65, 0x45, 0x78, 0x65, 0x63, 0x75, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x1c, 0x0a, 0x1a, 0x4d, 0x75, 0x6c, 0x74, 0x69, 0x70,
	0x6c, 0x65, 0x45, 0x78, 0x65, 0x63, 0x75, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x32, 0xb5, 0x01, 0x0a, 0x15, 0x44, 0x69, 0x66, 0x66, 0x65, 0x72, 0x65,
	0x6e, 0x74, 0x69, 0x61, 0x6c, 0x45, 0x76, 0x6f, 0x6c, 0x75, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x3d,
	0x0a, 0x07, 0x45, 0x78, 0x65, 0x63, 0x75, 0x74, 0x65, 0x12, 0x18, 0x2e, 0x61, 0x70, 0x69, 0x2e,
	0x76, 0x31, 0x2e, 0x45, 0x78, 0x65, 0x63, 0x75, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x18, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x76, 0x31, 0x2e, 0x45, 0x78, 0x65,
	0x63, 0x75, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x5d, 0x0a,
	0x12, 0x4d, 0x75, 0x6c, 0x74, 0x69, 0x70, 0x6c, 0x65, 0x45, 0x78, 0x65, 0x63, 0x75, 0x74, 0x69,
	0x6f, 0x6e, 0x73, 0x12, 0x21, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x76, 0x31, 0x2e, 0x4d, 0x75, 0x6c,
	0x74, 0x69, 0x70, 0x6c, 0x65, 0x45, 0x78, 0x65, 0x63, 0x75, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x22, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x76, 0x31, 0x2e,
	0x4d, 0x75, 0x6c, 0x74, 0x69, 0x70, 0x6c, 0x65, 0x45, 0x78, 0x65, 0x63, 0x75, 0x74, 0x69, 0x6f,
	0x6e, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x30, 0x01, 0x42, 0x09, 0x5a, 0x07,
	0x70, 0x6b, 0x67, 0x2f, 0x61, 0x70, 0x69, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_api_v1_differential_evolution_proto_rawDescOnce sync.Once
	file_api_v1_differential_evolution_proto_rawDescData = file_api_v1_differential_evolution_proto_rawDesc
)

func file_api_v1_differential_evolution_proto_rawDescGZIP() []byte {
	file_api_v1_differential_evolution_proto_rawDescOnce.Do(func() {
		file_api_v1_differential_evolution_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_v1_differential_evolution_proto_rawDescData)
	})
	return file_api_v1_differential_evolution_proto_rawDescData
}

var file_api_v1_differential_evolution_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_api_v1_differential_evolution_proto_goTypes = []interface{}{
	(*Vector)(nil),                     // 0: api.v1.Vector
	(*Population)(nil),                 // 1: api.v1.Population
	(*PopulationParameters)(nil),       // 2: api.v1.PopulationParameters
	(*ExecutionRequest)(nil),           // 3: api.v1.ExecutionRequest
	(*ExecutionReponse)(nil),           // 4: api.v1.ExecutionReponse
	(*MultipleExecutionsRequest)(nil),  // 5: api.v1.MultipleExecutionsRequest
	(*MultipleExecutionsResponse)(nil), // 6: api.v1.MultipleExecutionsResponse
}
var file_api_v1_differential_evolution_proto_depIdxs = []int32{
	0, // 0: api.v1.Population.vectors:type_name -> api.v1.Vector
	3, // 1: api.v1.DifferentialEvolution.Execute:input_type -> api.v1.ExecutionRequest
	5, // 2: api.v1.DifferentialEvolution.MultipleExecutions:input_type -> api.v1.MultipleExecutionsRequest
	4, // 3: api.v1.DifferentialEvolution.Execute:output_type -> api.v1.ExecutionReponse
	6, // 4: api.v1.DifferentialEvolution.MultipleExecutions:output_type -> api.v1.MultipleExecutionsResponse
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_api_v1_differential_evolution_proto_init() }
func file_api_v1_differential_evolution_proto_init() {
	if File_api_v1_differential_evolution_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_v1_differential_evolution_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Vector); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1_differential_evolution_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Population); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1_differential_evolution_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PopulationParameters); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1_differential_evolution_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ExecutionRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1_differential_evolution_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ExecutionReponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1_differential_evolution_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MultipleExecutionsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1_differential_evolution_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MultipleExecutionsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_v1_differential_evolution_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_v1_differential_evolution_proto_goTypes,
		DependencyIndexes: file_api_v1_differential_evolution_proto_depIdxs,
		MessageInfos:      file_api_v1_differential_evolution_proto_msgTypes,
	}.Build()
	File_api_v1_differential_evolution_proto = out.File
	file_api_v1_differential_evolution_proto_rawDesc = nil
	file_api_v1_differential_evolution_proto_goTypes = nil
	file_api_v1_differential_evolution_proto_depIdxs = nil
}
