// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: api/v1/differential_evolution.proto

package api

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ListSupportedAlgorithmsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Algorithms    []string               `protobuf:"bytes,1,rep,name=algorithms,proto3" json:"algorithms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSupportedAlgorithmsResponse) Reset() {
	*x = ListSupportedAlgorithmsResponse{}
	mi := &file_api_v1_differential_evolution_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSupportedAlgorithmsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSupportedAlgorithmsResponse) ProtoMessage() {}

func (x *ListSupportedAlgorithmsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_differential_evolution_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSupportedAlgorithmsResponse.ProtoReflect.Descriptor instead.
func (*ListSupportedAlgorithmsResponse) Descriptor() ([]byte, []int) {
	return file_api_v1_differential_evolution_proto_rawDescGZIP(), []int{0}
}

func (x *ListSupportedAlgorithmsResponse) GetAlgorithms() []string {
	if x != nil {
		return x.Algorithms
	}
	return nil
}

type Variant struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Variant) Reset() {
	*x = Variant{}
	mi := &file_api_v1_differential_evolution_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Variant) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Variant) ProtoMessage() {}

func (x *Variant) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_differential_evolution_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Variant.ProtoReflect.Descriptor instead.
func (*Variant) Descriptor() ([]byte, []int) {
	return file_api_v1_differential_evolution_proto_rawDescGZIP(), []int{1}
}

func (x *Variant) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Variant) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type ListSupportedVariantsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Variants      []*Variant             `protobuf:"bytes,1,rep,name=variants,proto3" json:"variants,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSupportedVariantsResponse) Reset() {
	*x = ListSupportedVariantsResponse{}
	mi := &file_api_v1_differential_evolution_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSupportedVariantsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSupportedVariantsResponse) ProtoMessage() {}

func (x *ListSupportedVariantsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_differential_evolution_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSupportedVariantsResponse.ProtoReflect.Descriptor instead.
func (*ListSupportedVariantsResponse) Descriptor() ([]byte, []int) {
	return file_api_v1_differential_evolution_proto_rawDescGZIP(), []int{2}
}

func (x *ListSupportedVariantsResponse) GetVariants() []*Variant {
	if x != nil {
		return x.Variants
	}
	return nil
}

type Problem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Problem) Reset() {
	*x = Problem{}
	mi := &file_api_v1_differential_evolution_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Problem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Problem) ProtoMessage() {}

func (x *Problem) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_differential_evolution_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Problem.ProtoReflect.Descriptor instead.
func (*Problem) Descriptor() ([]byte, []int) {
	return file_api_v1_differential_evolution_proto_rawDescGZIP(), []int{3}
}

func (x *Problem) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Problem) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type ListSupportedProblemsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Problems      []*Problem             `protobuf:"bytes,1,rep,name=problems,proto3" json:"problems,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSupportedProblemsResponse) Reset() {
	*x = ListSupportedProblemsResponse{}
	mi := &file_api_v1_differential_evolution_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSupportedProblemsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSupportedProblemsResponse) ProtoMessage() {}

func (x *ListSupportedProblemsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_differential_evolution_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSupportedProblemsResponse.ProtoReflect.Descriptor instead.
func (*ListSupportedProblemsResponse) Descriptor() ([]byte, []int) {
	return file_api_v1_differential_evolution_proto_rawDescGZIP(), []int{4}
}

func (x *ListSupportedProblemsResponse) GetProblems() []*Problem {
	if x != nil {
		return x.Problems
	}
	return nil
}

type RunRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Algorithm     string                 `protobuf:"bytes,1,opt,name=algorithm,proto3" json:"algorithm,omitempty"`
	Variant       string                 `protobuf:"bytes,2,opt,name=variant,proto3" json:"variant,omitempty"`
	Problem       string                 `protobuf:"bytes,3,opt,name=problem,proto3" json:"problem,omitempty"`
	DeConfig      *DEConfig              `protobuf:"bytes,4,opt,name=de_config,json=deConfig,proto3" json:"de_config,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RunRequest) Reset() {
	*x = RunRequest{}
	mi := &file_api_v1_differential_evolution_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunRequest) ProtoMessage() {}

func (x *RunRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_differential_evolution_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunRequest.ProtoReflect.Descriptor instead.
func (*RunRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_differential_evolution_proto_rawDescGZIP(), []int{5}
}

func (x *RunRequest) GetAlgorithm() string {
	if x != nil {
		return x.Algorithm
	}
	return ""
}

func (x *RunRequest) GetVariant() string {
	if x != nil {
		return x.Variant
	}
	return ""
}

func (x *RunRequest) GetProblem() string {
	if x != nil {
		return x.Problem
	}
	return ""
}

func (x *RunRequest) GetDeConfig() *DEConfig {
	if x != nil {
		return x.DeConfig
	}
	return nil
}

type RunResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pareto        *Pareto                `protobuf:"bytes,1,opt,name=pareto,proto3" json:"pareto,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RunResponse) Reset() {
	*x = RunResponse{}
	mi := &file_api_v1_differential_evolution_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunResponse) ProtoMessage() {}

func (x *RunResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_differential_evolution_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunResponse.ProtoReflect.Descriptor instead.
func (*RunResponse) Descriptor() ([]byte, []int) {
	return file_api_v1_differential_evolution_proto_rawDescGZIP(), []int{6}
}

func (x *RunResponse) GetPareto() *Pareto {
	if x != nil {
		return x.Pareto
	}
	return nil
}

var File_api_v1_differential_evolution_proto protoreflect.FileDescriptor

const file_api_v1_differential_evolution_proto_rawDesc = "" +
	"\n" +
	"#api/v1/differential_evolution.proto\x12\x06api.v1\x1a\x18api/v1/definitions.proto\x1a*api/v1/differential_evolution_config.proto\x1a\x1cgoogle/api/annotations.proto\x1a\x1bgoogle/protobuf/empty.proto\"A\n" +
	"\x1fListSupportedAlgorithmsResponse\x12\x1e\n" +
	"\n" +
	"algorithms\x18\x01 \x03(\tR\n" +
	"algorithms\"?\n" +
	"\aVariant\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\"L\n" +
	"\x1dListSupportedVariantsResponse\x12+\n" +
	"\bvariants\x18\x01 \x03(\v2\x0f.api.v1.VariantR\bvariants\"?\n" +
	"\aProblem\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\"L\n" +
	"\x1dListSupportedProblemsResponse\x12+\n" +
	"\bproblems\x18\x01 \x03(\v2\x0f.api.v1.ProblemR\bproblems\"\x8d\x01\n" +
	"\n" +
	"RunRequest\x12\x1c\n" +
	"\talgorithm\x18\x01 \x01(\tR\talgorithm\x12\x18\n" +
	"\avariant\x18\x02 \x01(\tR\avariant\x12\x18\n" +
	"\aproblem\x18\x03 \x01(\tR\aproblem\x12-\n" +
	"\tde_config\x18\x04 \x01(\v2\x10.api.v1.DEConfigR\bdeConfig\"5\n" +
	"\vRunResponse\x12&\n" +
	"\x06pareto\x18\x01 \x01(\v2\x0e.api.v1.ParetoR\x06pareto2\xdc\x03\n" +
	"\x1cDifferentialEvolutionService\x12\x7f\n" +
	"\x17ListSupportedAlgorithms\x12\x16.google.protobuf.Empty\x1a'.api.v1.ListSupportedAlgorithmsResponse\"#\x82\xd3\xe4\x93\x02\x1d\x12\x1b/v1/de/supported/algorithms\x12y\n" +
	"\x15ListSupportedVariants\x12\x16.google.protobuf.Empty\x1a%.api.v1.ListSupportedVariantsResponse\"!\x82\xd3\xe4\x93\x02\x1b\x12\x19/v1/de/supported/variants\x12y\n" +
	"\x15ListSupportedProblems\x12\x16.google.protobuf.Empty\x1a%.api.v1.ListSupportedProblemsResponse\"!\x82\xd3\xe4\x93\x02\x1b\x12\x19/v1/de/supported/problems\x12E\n" +
	"\x03Run\x12\x12.api.v1.RunRequest\x1a\x13.api.v1.RunResponse\"\x15\x82\xd3\xe4\x93\x02\x0f:\x01*\"\n" +
	"/v1/de/runB\tZ\apkg/apib\x06proto3"

var (
	file_api_v1_differential_evolution_proto_rawDescOnce sync.Once
	file_api_v1_differential_evolution_proto_rawDescData []byte
)

func file_api_v1_differential_evolution_proto_rawDescGZIP() []byte {
	file_api_v1_differential_evolution_proto_rawDescOnce.Do(func() {
		file_api_v1_differential_evolution_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_v1_differential_evolution_proto_rawDesc), len(file_api_v1_differential_evolution_proto_rawDesc)))
	})
	return file_api_v1_differential_evolution_proto_rawDescData
}

var file_api_v1_differential_evolution_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_api_v1_differential_evolution_proto_goTypes = []any{
	(*ListSupportedAlgorithmsResponse)(nil), // 0: api.v1.ListSupportedAlgorithmsResponse
	(*Variant)(nil),                         // 1: api.v1.Variant
	(*ListSupportedVariantsResponse)(nil),   // 2: api.v1.ListSupportedVariantsResponse
	(*Problem)(nil),                         // 3: api.v1.Problem
	(*ListSupportedProblemsResponse)(nil),   // 4: api.v1.ListSupportedProblemsResponse
	(*RunRequest)(nil),                      // 5: api.v1.RunRequest
	(*RunResponse)(nil),                     // 6: api.v1.RunResponse
	(*DEConfig)(nil),                        // 7: api.v1.DEConfig
	(*Pareto)(nil),                          // 8: api.v1.Pareto
	(*emptypb.Empty)(nil),                   // 9: google.protobuf.Empty
}
var file_api_v1_differential_evolution_proto_depIdxs = []int32{
	1, // 0: api.v1.ListSupportedVariantsResponse.variants:type_name -> api.v1.Variant
	3, // 1: api.v1.ListSupportedProblemsResponse.problems:type_name -> api.v1.Problem
	7, // 2: api.v1.RunRequest.de_config:type_name -> api.v1.DEConfig
	8, // 3: api.v1.RunResponse.pareto:type_name -> api.v1.Pareto
	9, // 4: api.v1.DifferentialEvolutionService.ListSupportedAlgorithms:input_type -> google.protobuf.Empty
	9, // 5: api.v1.DifferentialEvolutionService.ListSupportedVariants:input_type -> google.protobuf.Empty
	9, // 6: api.v1.DifferentialEvolutionService.ListSupportedProblems:input_type -> google.protobuf.Empty
	5, // 7: api.v1.DifferentialEvolutionService.Run:input_type -> api.v1.RunRequest
	0, // 8: api.v1.DifferentialEvolutionService.ListSupportedAlgorithms:output_type -> api.v1.ListSupportedAlgorithmsResponse
	2, // 9: api.v1.DifferentialEvolutionService.ListSupportedVariants:output_type -> api.v1.ListSupportedVariantsResponse
	4, // 10: api.v1.DifferentialEvolutionService.ListSupportedProblems:output_type -> api.v1.ListSupportedProblemsResponse
	6, // 11: api.v1.DifferentialEvolutionService.Run:output_type -> api.v1.RunResponse
	8, // [8:12] is the sub-list for method output_type
	4, // [4:8] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_api_v1_differential_evolution_proto_init() }
func file_api_v1_differential_evolution_proto_init() {
	if File_api_v1_differential_evolution_proto != nil {
		return
	}
	file_api_v1_definitions_proto_init()
	file_api_v1_differential_evolution_config_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_v1_differential_evolution_proto_rawDesc), len(file_api_v1_differential_evolution_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_v1_differential_evolution_proto_goTypes,
		DependencyIndexes: file_api_v1_differential_evolution_proto_depIdxs,
		MessageInfos:      file_api_v1_differential_evolution_proto_msgTypes,
	}.Build()
	File_api_v1_differential_evolution_proto = out.File
	file_api_v1_differential_evolution_proto_goTypes = nil
	file_api_v1_differential_evolution_proto_depIdxs = nil
}
