// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        (unknown)
// source: api/v1/differential_evolution_config.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DEConfig struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Executions          int64 `protobuf:"varint,1,opt,name=executions,proto3" json:"executions,omitempty"`
	Generations         int64 `protobuf:"varint,2,opt,name=generations,proto3" json:"generations,omitempty"`
	Dimensions          int64 `protobuf:"varint,3,opt,name=dimensions,proto3" json:"dimensions,omitempty"`
	ObjectiveFuncAmount int64 `protobuf:"varint,4,opt,name=objective_func_amount,json=objectiveFuncAmount,proto3" json:"objective_func_amount,omitempty"`
	// Types that are assignable to AlgorithmConfig:
	//
	//	*DEConfig_Gde3
	AlgorithmConfig isDEConfig_AlgorithmConfig `protobuf_oneof:"algorithm_config"`
}

func (x *DEConfig) Reset() {
	*x = DEConfig{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_differential_evolution_config_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DEConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DEConfig) ProtoMessage() {}

func (x *DEConfig) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_differential_evolution_config_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DEConfig.ProtoReflect.Descriptor instead.
func (*DEConfig) Descriptor() ([]byte, []int) {
	return file_api_v1_differential_evolution_config_proto_rawDescGZIP(), []int{0}
}

func (x *DEConfig) GetExecutions() int64 {
	if x != nil {
		return x.Executions
	}
	return 0
}

func (x *DEConfig) GetGenerations() int64 {
	if x != nil {
		return x.Generations
	}
	return 0
}

func (x *DEConfig) GetDimensions() int64 {
	if x != nil {
		return x.Dimensions
	}
	return 0
}

func (x *DEConfig) GetObjectiveFuncAmount() int64 {
	if x != nil {
		return x.ObjectiveFuncAmount
	}
	return 0
}

func (m *DEConfig) GetAlgorithmConfig() isDEConfig_AlgorithmConfig {
	if m != nil {
		return m.AlgorithmConfig
	}
	return nil
}

func (x *DEConfig) GetGde3() *GDE3Config {
	if x, ok := x.GetAlgorithmConfig().(*DEConfig_Gde3); ok {
		return x.Gde3
	}
	return nil
}

type isDEConfig_AlgorithmConfig interface {
	isDEConfig_AlgorithmConfig()
}

type DEConfig_Gde3 struct {
	Gde3 *GDE3Config `protobuf:"bytes,5,opt,name=gde3,proto3,oneof"`
}

func (*DEConfig_Gde3) isDEConfig_AlgorithmConfig() {}

type GDE3Config struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Cr float32 `protobuf:"fixed32,1,opt,name=cr,proto3" json:"cr,omitempty"`
	F  float32 `protobuf:"fixed32,2,opt,name=f,proto3" json:"f,omitempty"`
	P  float32 `protobuf:"fixed32,3,opt,name=p,proto3" json:"p,omitempty"`
}

func (x *GDE3Config) Reset() {
	*x = GDE3Config{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_differential_evolution_config_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GDE3Config) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GDE3Config) ProtoMessage() {}

func (x *GDE3Config) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_differential_evolution_config_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GDE3Config.ProtoReflect.Descriptor instead.
func (*GDE3Config) Descriptor() ([]byte, []int) {
	return file_api_v1_differential_evolution_config_proto_rawDescGZIP(), []int{1}
}

func (x *GDE3Config) GetCr() float32 {
	if x != nil {
		return x.Cr
	}
	return 0
}

func (x *GDE3Config) GetF() float32 {
	if x != nil {
		return x.F
	}
	return 0
}

func (x *GDE3Config) GetP() float32 {
	if x != nil {
		return x.P
	}
	return 0
}

var File_api_v1_differential_evolution_config_proto protoreflect.FileDescriptor

var file_api_v1_differential_evolution_config_proto_rawDesc = []byte{
	0x0a, 0x2a, 0x61, 0x70, 0x69, 0x2f, 0x76, 0x31, 0x2f, 0x64, 0x69, 0x66, 0x66, 0x65, 0x72, 0x65,
	0x6e, 0x74, 0x69, 0x61, 0x6c, 0x5f, 0x65, 0x76, 0x6f, 0x6c, 0x75, 0x74, 0x69, 0x6f, 0x6e, 0x5f,
	0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06, 0x61, 0x70,
	0x69, 0x2e, 0x76, 0x31, 0x22, 0xde, 0x01, 0x0a, 0x08, 0x44, 0x45, 0x43, 0x6f, 0x6e, 0x66, 0x69,
	0x67, 0x12, 0x1e, 0x0a, 0x0a, 0x65, 0x78, 0x65, 0x63, 0x75, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0a, 0x65, 0x78, 0x65, 0x63, 0x75, 0x74, 0x69, 0x6f, 0x6e,
	0x73, 0x12, 0x20, 0x0a, 0x0b, 0x67, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0b, 0x67, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x73, 0x12, 0x1e, 0x0a, 0x0a, 0x64, 0x69, 0x6d, 0x65, 0x6e, 0x73, 0x69, 0x6f, 0x6e,
	0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0a, 0x64, 0x69, 0x6d, 0x65, 0x6e, 0x73, 0x69,
	0x6f, 0x6e, 0x73, 0x12, 0x32, 0x0a, 0x15, 0x6f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x69, 0x76, 0x65,
	0x5f, 0x66, 0x75, 0x6e, 0x63, 0x5f, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x13, 0x6f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x69, 0x76, 0x65, 0x46, 0x75, 0x6e,
	0x63, 0x41, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x28, 0x0a, 0x04, 0x67, 0x64, 0x65, 0x33, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x76, 0x31, 0x2e, 0x47,
	0x44, 0x45, 0x33, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x48, 0x00, 0x52, 0x04, 0x67, 0x64, 0x65,
	0x33, 0x42, 0x12, 0x0a, 0x10, 0x61, 0x6c, 0x67, 0x6f, 0x72, 0x69, 0x74, 0x68, 0x6d, 0x5f, 0x63,
	0x6f, 0x6e, 0x66, 0x69, 0x67, 0x22, 0x38, 0x0a, 0x0a, 0x47, 0x44, 0x45, 0x33, 0x43, 0x6f, 0x6e,
	0x66, 0x69, 0x67, 0x12, 0x0e, 0x0a, 0x02, 0x63, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x02, 0x52,
	0x02, 0x63, 0x72, 0x12, 0x0c, 0x0a, 0x01, 0x66, 0x18, 0x02, 0x20, 0x01, 0x28, 0x02, 0x52, 0x01,
	0x66, 0x12, 0x0c, 0x0a, 0x01, 0x70, 0x18, 0x03, 0x20, 0x01, 0x28, 0x02, 0x52, 0x01, 0x70, 0x42,
	0x09, 0x5a, 0x07, 0x70, 0x6b, 0x67, 0x2f, 0x61, 0x70, 0x69, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_api_v1_differential_evolution_config_proto_rawDescOnce sync.Once
	file_api_v1_differential_evolution_config_proto_rawDescData = file_api_v1_differential_evolution_config_proto_rawDesc
)

func file_api_v1_differential_evolution_config_proto_rawDescGZIP() []byte {
	file_api_v1_differential_evolution_config_proto_rawDescOnce.Do(func() {
		file_api_v1_differential_evolution_config_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_v1_differential_evolution_config_proto_rawDescData)
	})
	return file_api_v1_differential_evolution_config_proto_rawDescData
}

var file_api_v1_differential_evolution_config_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_api_v1_differential_evolution_config_proto_goTypes = []interface{}{
	(*DEConfig)(nil),   // 0: api.v1.DEConfig
	(*GDE3Config)(nil), // 1: api.v1.GDE3Config
}
var file_api_v1_differential_evolution_config_proto_depIdxs = []int32{
	1, // 0: api.v1.DEConfig.gde3:type_name -> api.v1.GDE3Config
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_api_v1_differential_evolution_config_proto_init() }
func file_api_v1_differential_evolution_config_proto_init() {
	if File_api_v1_differential_evolution_config_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_v1_differential_evolution_config_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DEConfig); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1_differential_evolution_config_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GDE3Config); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_api_v1_differential_evolution_config_proto_msgTypes[0].OneofWrappers = []interface{}{
		(*DEConfig_Gde3)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_v1_differential_evolution_config_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_v1_differential_evolution_config_proto_goTypes,
		DependencyIndexes: file_api_v1_differential_evolution_config_proto_depIdxs,
		MessageInfos:      file_api_v1_differential_evolution_config_proto_msgTypes,
	}.Build()
	File_api_v1_differential_evolution_config_proto = out.File
	file_api_v1_differential_evolution_config_proto_rawDesc = nil
	file_api_v1_differential_evolution_config_proto_goTypes = nil
	file_api_v1_differential_evolution_config_proto_depIdxs = nil
}
