// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: api/v1/pareto_set.proto

package api

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ParetoServiceCreateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pareto        *Pareto                `protobuf:"bytes,1,opt,name=pareto,proto3" json:"pareto,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ParetoServiceCreateRequest) Reset() {
	*x = ParetoServiceCreateRequest{}
	mi := &file_api_v1_pareto_set_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ParetoServiceCreateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ParetoServiceCreateRequest) ProtoMessage() {}

func (x *ParetoServiceCreateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_pareto_set_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ParetoServiceCreateRequest.ProtoReflect.Descriptor instead.
func (*ParetoServiceCreateRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_pareto_set_proto_rawDescGZIP(), []int{0}
}

func (x *ParetoServiceCreateRequest) GetPareto() *Pareto {
	if x != nil {
		return x.Pareto
	}
	return nil
}

type ParetoServiceGetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ParetoIds     *ParetoIDs             `protobuf:"bytes,1,opt,name=pareto_ids,json=paretoIds,proto3" json:"pareto_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ParetoServiceGetRequest) Reset() {
	*x = ParetoServiceGetRequest{}
	mi := &file_api_v1_pareto_set_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ParetoServiceGetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ParetoServiceGetRequest) ProtoMessage() {}

func (x *ParetoServiceGetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_pareto_set_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ParetoServiceGetRequest.ProtoReflect.Descriptor instead.
func (*ParetoServiceGetRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_pareto_set_proto_rawDescGZIP(), []int{1}
}

func (x *ParetoServiceGetRequest) GetParetoIds() *ParetoIDs {
	if x != nil {
		return x.ParetoIds
	}
	return nil
}

type ParetoServiceGetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pareto        *Pareto                `protobuf:"bytes,1,opt,name=pareto,proto3" json:"pareto,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ParetoServiceGetResponse) Reset() {
	*x = ParetoServiceGetResponse{}
	mi := &file_api_v1_pareto_set_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ParetoServiceGetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ParetoServiceGetResponse) ProtoMessage() {}

func (x *ParetoServiceGetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_pareto_set_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ParetoServiceGetResponse.ProtoReflect.Descriptor instead.
func (*ParetoServiceGetResponse) Descriptor() ([]byte, []int) {
	return file_api_v1_pareto_set_proto_rawDescGZIP(), []int{2}
}

func (x *ParetoServiceGetResponse) GetPareto() *Pareto {
	if x != nil {
		return x.Pareto
	}
	return nil
}

type ParetoServiceUpdateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pareto        *Pareto                `protobuf:"bytes,1,opt,name=pareto,proto3" json:"pareto,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ParetoServiceUpdateRequest) Reset() {
	*x = ParetoServiceUpdateRequest{}
	mi := &file_api_v1_pareto_set_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ParetoServiceUpdateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ParetoServiceUpdateRequest) ProtoMessage() {}

func (x *ParetoServiceUpdateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_pareto_set_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ParetoServiceUpdateRequest.ProtoReflect.Descriptor instead.
func (*ParetoServiceUpdateRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_pareto_set_proto_rawDescGZIP(), []int{3}
}

func (x *ParetoServiceUpdateRequest) GetPareto() *Pareto {
	if x != nil {
		return x.Pareto
	}
	return nil
}

type ParetoServiceDeleteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ParetoIds     *ParetoIDs             `protobuf:"bytes,1,opt,name=pareto_ids,json=paretoIds,proto3" json:"pareto_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ParetoServiceDeleteRequest) Reset() {
	*x = ParetoServiceDeleteRequest{}
	mi := &file_api_v1_pareto_set_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ParetoServiceDeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ParetoServiceDeleteRequest) ProtoMessage() {}

func (x *ParetoServiceDeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_pareto_set_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ParetoServiceDeleteRequest.ProtoReflect.Descriptor instead.
func (*ParetoServiceDeleteRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_pareto_set_proto_rawDescGZIP(), []int{4}
}

func (x *ParetoServiceDeleteRequest) GetParetoIds() *ParetoIDs {
	if x != nil {
		return x.ParetoIds
	}
	return nil
}

type ParetoServiceListByUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserIds       *UserIDs               `protobuf:"bytes,1,opt,name=user_ids,json=userIds,proto3" json:"user_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ParetoServiceListByUserRequest) Reset() {
	*x = ParetoServiceListByUserRequest{}
	mi := &file_api_v1_pareto_set_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ParetoServiceListByUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ParetoServiceListByUserRequest) ProtoMessage() {}

func (x *ParetoServiceListByUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_pareto_set_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ParetoServiceListByUserRequest.ProtoReflect.Descriptor instead.
func (*ParetoServiceListByUserRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_pareto_set_proto_rawDescGZIP(), []int{5}
}

func (x *ParetoServiceListByUserRequest) GetUserIds() *UserIDs {
	if x != nil {
		return x.UserIds
	}
	return nil
}

type ParetoServiceListByUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pareto        *Pareto                `protobuf:"bytes,1,opt,name=pareto,proto3" json:"pareto,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ParetoServiceListByUserResponse) Reset() {
	*x = ParetoServiceListByUserResponse{}
	mi := &file_api_v1_pareto_set_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ParetoServiceListByUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ParetoServiceListByUserResponse) ProtoMessage() {}

func (x *ParetoServiceListByUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_pareto_set_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ParetoServiceListByUserResponse.ProtoReflect.Descriptor instead.
func (*ParetoServiceListByUserResponse) Descriptor() ([]byte, []int) {
	return file_api_v1_pareto_set_proto_rawDescGZIP(), []int{6}
}

func (x *ParetoServiceListByUserResponse) GetPareto() *Pareto {
	if x != nil {
		return x.Pareto
	}
	return nil
}

var File_api_v1_pareto_set_proto protoreflect.FileDescriptor

const file_api_v1_pareto_set_proto_rawDesc = "" +
	"\n" +
	"\x17api/v1/pareto_set.proto\x12\x06api.v1\x1a\x18api/v1/definitions.proto\x1a\x11api/v1/user.proto\x1a\x1cgoogle/api/annotations.proto\x1a\x1bgoogle/protobuf/empty.proto\"D\n" +
	"\x1aParetoServiceCreateRequest\x12&\n" +
	"\x06pareto\x18\x01 \x01(\v2\x0e.api.v1.ParetoR\x06pareto\"K\n" +
	"\x17ParetoServiceGetRequest\x120\n" +
	"\n" +
	"pareto_ids\x18\x01 \x01(\v2\x11.api.v1.ParetoIDsR\tparetoIds\"B\n" +
	"\x18ParetoServiceGetResponse\x12&\n" +
	"\x06pareto\x18\x01 \x01(\v2\x0e.api.v1.ParetoR\x06pareto\"D\n" +
	"\x1aParetoServiceUpdateRequest\x12&\n" +
	"\x06pareto\x18\x01 \x01(\v2\x0e.api.v1.ParetoR\x06pareto\"N\n" +
	"\x1aParetoServiceDeleteRequest\x120\n" +
	"\n" +
	"pareto_ids\x18\x01 \x01(\v2\x11.api.v1.ParetoIDsR\tparetoIds\"L\n" +
	"\x1eParetoServiceListByUserRequest\x12*\n" +
	"\buser_ids\x18\x01 \x01(\v2\x0f.api.v1.UserIDsR\auserIds\"I\n" +
	"\x1fParetoServiceListByUserResponse\x12&\n" +
	"\x06pareto\x18\x01 \x01(\v2\x0e.api.v1.ParetoR\x06pareto2\xf7\x02\n" +
	"\rParetoService\x12l\n" +
	"\x03Get\x12\x1f.api.v1.ParetoServiceGetRequest\x1a .api.v1.ParetoServiceGetResponse\"\"\x82\xd3\xe4\x93\x02\x1c\x12\x1a/v1/pareto/{pareto_ids.id}\x12m\n" +
	"\x06Delete\x12\".api.v1.ParetoServiceDeleteRequest\x1a\x16.google.protobuf.Empty\"'\x82\xd3\xe4\x93\x02!*\x1f/v1/pareto/{pareto_ids.user_id}\x12\x88\x01\n" +
	"\n" +
	"ListByUser\x12&.api.v1.ParetoServiceListByUserRequest\x1a'.api.v1.ParetoServiceListByUserResponse\"'\x82\xd3\xe4\x93\x02!\x12\x1f/v1/paretos/{user_ids.username}0\x01B\tZ\apkg/apib\x06proto3"

var (
	file_api_v1_pareto_set_proto_rawDescOnce sync.Once
	file_api_v1_pareto_set_proto_rawDescData []byte
)

func file_api_v1_pareto_set_proto_rawDescGZIP() []byte {
	file_api_v1_pareto_set_proto_rawDescOnce.Do(func() {
		file_api_v1_pareto_set_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_v1_pareto_set_proto_rawDesc), len(file_api_v1_pareto_set_proto_rawDesc)))
	})
	return file_api_v1_pareto_set_proto_rawDescData
}

var file_api_v1_pareto_set_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_api_v1_pareto_set_proto_goTypes = []any{
	(*ParetoServiceCreateRequest)(nil),      // 0: api.v1.ParetoServiceCreateRequest
	(*ParetoServiceGetRequest)(nil),         // 1: api.v1.ParetoServiceGetRequest
	(*ParetoServiceGetResponse)(nil),        // 2: api.v1.ParetoServiceGetResponse
	(*ParetoServiceUpdateRequest)(nil),      // 3: api.v1.ParetoServiceUpdateRequest
	(*ParetoServiceDeleteRequest)(nil),      // 4: api.v1.ParetoServiceDeleteRequest
	(*ParetoServiceListByUserRequest)(nil),  // 5: api.v1.ParetoServiceListByUserRequest
	(*ParetoServiceListByUserResponse)(nil), // 6: api.v1.ParetoServiceListByUserResponse
	(*Pareto)(nil),                          // 7: api.v1.Pareto
	(*ParetoIDs)(nil),                       // 8: api.v1.ParetoIDs
	(*UserIDs)(nil),                         // 9: api.v1.UserIDs
	(*emptypb.Empty)(nil),                   // 10: google.protobuf.Empty
}
var file_api_v1_pareto_set_proto_depIdxs = []int32{
	7,  // 0: api.v1.ParetoServiceCreateRequest.pareto:type_name -> api.v1.Pareto
	8,  // 1: api.v1.ParetoServiceGetRequest.pareto_ids:type_name -> api.v1.ParetoIDs
	7,  // 2: api.v1.ParetoServiceGetResponse.pareto:type_name -> api.v1.Pareto
	7,  // 3: api.v1.ParetoServiceUpdateRequest.pareto:type_name -> api.v1.Pareto
	8,  // 4: api.v1.ParetoServiceDeleteRequest.pareto_ids:type_name -> api.v1.ParetoIDs
	9,  // 5: api.v1.ParetoServiceListByUserRequest.user_ids:type_name -> api.v1.UserIDs
	7,  // 6: api.v1.ParetoServiceListByUserResponse.pareto:type_name -> api.v1.Pareto
	1,  // 7: api.v1.ParetoService.Get:input_type -> api.v1.ParetoServiceGetRequest
	4,  // 8: api.v1.ParetoService.Delete:input_type -> api.v1.ParetoServiceDeleteRequest
	5,  // 9: api.v1.ParetoService.ListByUser:input_type -> api.v1.ParetoServiceListByUserRequest
	2,  // 10: api.v1.ParetoService.Get:output_type -> api.v1.ParetoServiceGetResponse
	10, // 11: api.v1.ParetoService.Delete:output_type -> google.protobuf.Empty
	6,  // 12: api.v1.ParetoService.ListByUser:output_type -> api.v1.ParetoServiceListByUserResponse
	10, // [10:13] is the sub-list for method output_type
	7,  // [7:10] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_api_v1_pareto_set_proto_init() }
func file_api_v1_pareto_set_proto_init() {
	if File_api_v1_pareto_set_proto != nil {
		return
	}
	file_api_v1_definitions_proto_init()
	file_api_v1_user_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_v1_pareto_set_proto_rawDesc), len(file_api_v1_pareto_set_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_v1_pareto_set_proto_goTypes,
		DependencyIndexes: file_api_v1_pareto_set_proto_depIdxs,
		MessageInfos:      file_api_v1_pareto_set_proto_msgTypes,
	}.Build()
	File_api_v1_pareto_set_proto = out.File
	file_api_v1_pareto_set_proto_goTypes = nil
	file_api_v1_pareto_set_proto_depIdxs = nil
}
