// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        (unknown)
// source: api/v1/population.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Population struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Vectors []*Vector `protobuf:"bytes,1,rep,name=vectors,proto3" json:"vectors,omitempty"`
}

func (x *Population) Reset() {
	*x = Population{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_population_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Population) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Population) ProtoMessage() {}

func (x *Population) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_population_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Population.ProtoReflect.Descriptor instead.
func (*Population) Descriptor() ([]byte, []int) {
	return file_api_v1_population_proto_rawDescGZIP(), []int{0}
}

func (x *Population) GetVectors() []*Vector {
	if x != nil {
		return x.Vectors
	}
	return nil
}

type PopulationParameters struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DimensionsSize int64     `protobuf:"varint,1,opt,name=dimensions_size,json=dimensionsSize,proto3" json:"dimensions_size,omitempty"`
	ObjetivesSize  int64     `protobuf:"varint,2,opt,name=objetives_size,json=objetivesSize,proto3" json:"objetives_size,omitempty"`
	Floors         []float64 `protobuf:"fixed64,3,rep,packed,name=floors,proto3" json:"floors,omitempty"`
	Ceils          []float64 `protobuf:"fixed64,4,rep,packed,name=ceils,proto3" json:"ceils,omitempty"`
}

func (x *PopulationParameters) Reset() {
	*x = PopulationParameters{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_population_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PopulationParameters) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PopulationParameters) ProtoMessage() {}

func (x *PopulationParameters) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_population_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PopulationParameters.ProtoReflect.Descriptor instead.
func (*PopulationParameters) Descriptor() ([]byte, []int) {
	return file_api_v1_population_proto_rawDescGZIP(), []int{1}
}

func (x *PopulationParameters) GetDimensionsSize() int64 {
	if x != nil {
		return x.DimensionsSize
	}
	return 0
}

func (x *PopulationParameters) GetObjetivesSize() int64 {
	if x != nil {
		return x.ObjetivesSize
	}
	return 0
}

func (x *PopulationParameters) GetFloors() []float64 {
	if x != nil {
		return x.Floors
	}
	return nil
}

func (x *PopulationParameters) GetCeils() []float64 {
	if x != nil {
		return x.Ceils
	}
	return nil
}

var File_api_v1_population_proto protoreflect.FileDescriptor

var file_api_v1_population_proto_rawDesc = []byte{
	0x0a, 0x17, 0x61, 0x70, 0x69, 0x2f, 0x76, 0x31, 0x2f, 0x70, 0x6f, 0x70, 0x75, 0x6c, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06, 0x61, 0x70, 0x69, 0x2e, 0x76,
	0x31, 0x1a, 0x13, 0x61, 0x70, 0x69, 0x2f, 0x76, 0x31, 0x2f, 0x76, 0x65, 0x63, 0x74, 0x6f, 0x72,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x36, 0x0a, 0x0a, 0x50, 0x6f, 0x70, 0x75, 0x6c, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x12, 0x28, 0x0a, 0x07, 0x76, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x73, 0x18,
	0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x76, 0x31, 0x2e, 0x56,
	0x65, 0x63, 0x74, 0x6f, 0x72, 0x52, 0x07, 0x76, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x73, 0x22, 0x94,
	0x01, 0x0a, 0x14, 0x50, 0x6f, 0x70, 0x75, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x50, 0x61, 0x72,
	0x61, 0x6d, 0x65, 0x74, 0x65, 0x72, 0x73, 0x12, 0x27, 0x0a, 0x0f, 0x64, 0x69, 0x6d, 0x65, 0x6e,
	0x73, 0x69, 0x6f, 0x6e, 0x73, 0x5f, 0x73, 0x69, 0x7a, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x0e, 0x64, 0x69, 0x6d, 0x65, 0x6e, 0x73, 0x69, 0x6f, 0x6e, 0x73, 0x53, 0x69, 0x7a, 0x65,
	0x12, 0x25, 0x0a, 0x0e, 0x6f, 0x62, 0x6a, 0x65, 0x74, 0x69, 0x76, 0x65, 0x73, 0x5f, 0x73, 0x69,
	0x7a, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0d, 0x6f, 0x62, 0x6a, 0x65, 0x74, 0x69,
	0x76, 0x65, 0x73, 0x53, 0x69, 0x7a, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x66, 0x6c, 0x6f, 0x6f, 0x72,
	0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x01, 0x52, 0x06, 0x66, 0x6c, 0x6f, 0x6f, 0x72, 0x73, 0x12,
	0x14, 0x0a, 0x05, 0x63, 0x65, 0x69, 0x6c, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x01, 0x52, 0x05,
	0x63, 0x65, 0x69, 0x6c, 0x73, 0x42, 0x09, 0x5a, 0x07, 0x70, 0x6b, 0x67, 0x2f, 0x61, 0x70, 0x69,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_api_v1_population_proto_rawDescOnce sync.Once
	file_api_v1_population_proto_rawDescData = file_api_v1_population_proto_rawDesc
)

func file_api_v1_population_proto_rawDescGZIP() []byte {
	file_api_v1_population_proto_rawDescOnce.Do(func() {
		file_api_v1_population_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_v1_population_proto_rawDescData)
	})
	return file_api_v1_population_proto_rawDescData
}

var file_api_v1_population_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_api_v1_population_proto_goTypes = []interface{}{
	(*Population)(nil),           // 0: api.v1.Population
	(*PopulationParameters)(nil), // 1: api.v1.PopulationParameters
	(*Vector)(nil),               // 2: api.v1.Vector
}
var file_api_v1_population_proto_depIdxs = []int32{
	2, // 0: api.v1.Population.vectors:type_name -> api.v1.Vector
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_api_v1_population_proto_init() }
func file_api_v1_population_proto_init() {
	if File_api_v1_population_proto != nil {
		return
	}
	file_api_v1_vector_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_api_v1_population_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Population); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1_population_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PopulationParameters); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_v1_population_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_v1_population_proto_goTypes,
		DependencyIndexes: file_api_v1_population_proto_depIdxs,
		MessageInfos:      file_api_v1_population_proto_msgTypes,
	}.Build()
	File_api_v1_population_proto = out.File
	file_api_v1_population_proto_rawDesc = nil
	file_api_v1_population_proto_goTypes = nil
	file_api_v1_population_proto_depIdxs = nil
}
