// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: api/v1/tenant.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// TenantIDs is the standard tenant id message.
type TenantIDs struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TenantIDs) Reset() {
	*x = TenantIDs{}
	mi := &file_api_v1_tenant_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TenantIDs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TenantIDs) ProtoMessage() {}

func (x *TenantIDs) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_tenant_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TenantIDs.ProtoReflect.Descriptor instead.
func (*TenantIDs) Descriptor() ([]byte, []int) {
	return file_api_v1_tenant_proto_rawDescGZIP(), []int{0}
}

func (x *TenantIDs) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

// Contains the fields that belong to a tenant.
type Tenant struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ids           *TenantIDs             `protobuf:"bytes,1,opt,name=ids,proto3" json:"ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Tenant) Reset() {
	*x = Tenant{}
	mi := &file_api_v1_tenant_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Tenant) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Tenant) ProtoMessage() {}

func (x *Tenant) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_tenant_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Tenant.ProtoReflect.Descriptor instead.
func (*Tenant) Descriptor() ([]byte, []int) {
	return file_api_v1_tenant_proto_rawDescGZIP(), []int{1}
}

func (x *Tenant) GetIds() *TenantIDs {
	if x != nil {
		return x.Ids
	}
	return nil
}

var File_api_v1_tenant_proto protoreflect.FileDescriptor

const file_api_v1_tenant_proto_rawDesc = "" +
	"\n" +
	"\x13api/v1/tenant.proto\x12\x06api.v1\"(\n" +
	"\tTenantIDs\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\"-\n" +
	"\x06Tenant\x12#\n" +
	"\x03ids\x18\x01 \x01(\v2\x11.api.v1.TenantIDsR\x03idsB\tZ\apkg/apib\x06proto3"

var (
	file_api_v1_tenant_proto_rawDescOnce sync.Once
	file_api_v1_tenant_proto_rawDescData []byte
)

func file_api_v1_tenant_proto_rawDescGZIP() []byte {
	file_api_v1_tenant_proto_rawDescOnce.Do(func() {
		file_api_v1_tenant_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_v1_tenant_proto_rawDesc), len(file_api_v1_tenant_proto_rawDesc)))
	})
	return file_api_v1_tenant_proto_rawDescData
}

var file_api_v1_tenant_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_api_v1_tenant_proto_goTypes = []any{
	(*TenantIDs)(nil), // 0: api.v1.TenantIDs
	(*Tenant)(nil),    // 1: api.v1.Tenant
}
var file_api_v1_tenant_proto_depIdxs = []int32{
	0, // 0: api.v1.Tenant.ids:type_name -> api.v1.TenantIDs
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_api_v1_tenant_proto_init() }
func file_api_v1_tenant_proto_init() {
	if File_api_v1_tenant_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_v1_tenant_proto_rawDesc), len(file_api_v1_tenant_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_v1_tenant_proto_goTypes,
		DependencyIndexes: file_api_v1_tenant_proto_depIdxs,
		MessageInfos:      file_api_v1_tenant_proto_msgTypes,
	}.Build()
	File_api_v1_tenant_proto = out.File
	file_api_v1_tenant_proto_goTypes = nil
	file_api_v1_tenant_proto_depIdxs = nil
}
